"""Usage spec integration for click."""

from __future__ import annotations

import click

from usage_spec import Spec, SpecArg, SpecFlag, SpecCommand, SpecChoices, render_kdl, validate_kdl, render_json, generate as core_generate

from .convert import convert_root

__all__ = [
    "convert_root",
    "generate",
    "generate_kdl",
    "generate_json",
    "render_kdl",
    "Spec",
    "SpecArg",
    "SpecFlag",
    "SpecCommand",
    "SpecChoices",
]


def generate(cmd: click.BaseCommand, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format from a click Command/Group."""
    spec = convert_root(cmd, bin_name)
    return core_generate(spec, format="kdl", comment="@generated by usage-spec-click from click metadata")


def generate_kdl(cmd: click.BaseCommand, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format (alias for generate)."""
    return generate(cmd, bin_name)


def generate_json(cmd: click.BaseCommand, bin_name: str | None = None) -> str:
    """Generate usage spec in JSON format from a click Command/Group."""
    spec = convert_root(cmd, bin_name)
    return core_generate(spec, format="json")
