package picocli_usage

import picocli.CommandLine
import usage_spec.generate
import usage_spec.renderKDL
import usage_spec.renderJSON

fun generate(cmd: CommandLine, binName: String? = null): String {
    val spec = convertRoot(cmd, binName)
    return generate(spec, format = "kdl", comment = "@generated by picocli-usage from picocli metadata")
}

fun generateKDL(cmd: CommandLine, binName: String? = null): String {
    return generate(cmd, binName)
}

fun generateJSON(cmd: CommandLine, binName: String? = null): String {
    val spec = convertRoot(cmd, binName)
    return generate(spec, format = "json")
}
