"""Usage spec integration for Typer."""

from __future__ import annotations

import typer

from usage_spec import Spec, SpecArg, SpecFlag, SpecCommand, SpecChoices, render_kdl, validate_kdl, render_json, generate as core_generate

from .convert import convert_root

__all__ = [
    "convert_root",
    "generate",
    "generate_kdl",
    "generate_json",
    "render_kdl",
    "Spec",
    "SpecArg",
    "SpecFlag",
    "SpecCommand",
    "SpecChoices",
]


def generate(app: typer.Typer, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format from a Typer app."""
    spec = convert_root(app, bin_name)
    return core_generate(spec, format="kdl", comment="@generated by usage-spec-typer from Typer metadata")


def generate_kdl(app: typer.Typer, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format (alias for generate)."""
    return generate(app, bin_name)


def generate_json(app: typer.Typer, bin_name: str | None = None) -> str:
    """Generate usage spec in JSON format from a Typer app."""
    spec = convert_root(app, bin_name)
    return core_generate(spec, format="json")
