"""Usage spec integration for argparse."""

from __future__ import annotations

import argparse

from usage_spec import Spec, SpecArg, SpecFlag, SpecCommand, SpecChoices, render_kdl, validate_kdl, render_json, generate as core_generate

from .convert import convert_root

__all__ = [
    "convert_root",
    "generate",
    "generate_kdl",
    "generate_json",
    "render_kdl",
    "Spec",
    "SpecArg",
    "SpecFlag",
    "SpecCommand",
    "SpecChoices",
]


def generate(parser: argparse.ArgumentParser, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format from an argparse.ArgumentParser."""
    spec = convert_root(parser, bin_name)
    return core_generate(spec, format="kdl", comment="@generated by usage-spec-argparse from argparse metadata")


def generate_kdl(parser: argparse.ArgumentParser, bin_name: str | None = None) -> str:
    """Generate usage spec in KDL format (alias for generate)."""
    return generate(parser, bin_name)


def generate_json(parser: argparse.ArgumentParser, bin_name: str | None = None) -> str:
    """Generate usage spec in JSON format from an argparse.ArgumentParser."""
    spec = convert_root(parser, bin_name)
    return core_generate(spec, format="json")
