import { describe, it, expect } from "vitest";
import { generate, generateKDL, generateJSON, convertRoot } from "../src/index.js";
import type { OclifConfig, OclifCommand } from "../src/index.js";
import { validateKDL } from "@usage-spec/core";

function makeConfig(partial: Partial<OclifConfig> & { bin: string }): OclifConfig {
  return {
    version: "1.0.0",
    commands: [],
    topics: [],
    ...partial,
  };
}

describe("simple command", () => {
  it("generates spec for a basic CLI", () => {
    const config = makeConfig({
      bin: "mycli",
      commands: [
        {
          id: "mycli",
          flags: {
            verbose: { name: "verbose", type: "boolean", description: "Enable verbose output", char: "v" },
            config: { name: "config", type: "option", description: "Config file path", char: "c", helpValue: "<PATH>" },
          },
          args: {},
        },
      ],
    });

    const output = generate(config);

    expect(output).toContain("name mycli");
    expect(output).toContain("bin mycli");
    expect(output).toContain("version");
    expect(output).toContain("verbose");
    expect(output).toContain("config");
  });

  it("includes generated comment header", () => {
    const config = makeConfig({ bin: "app" });
    const output = generate(config);
    expect(output).toContain("// @generated by @usage-spec/oclif from oclif metadata");
  });
});

describe("version", () => {
  it("extracts version string", () => {
    const config = makeConfig({
      bin: "app",
      version: "2.0.0",
    });
    const spec = convertRoot(config);
    expect(spec.version).toBe("2.0.0");
  });

  it("uses empty string when version not set", () => {
    const config: OclifConfig = { bin: "app", commands: [], topics: [] };
    const spec = convertRoot(config);
    expect(spec.version).toBe("");
  });
});

describe("about/description", () => {
  it("extracts summary as about", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: {},
        summary: "A simple CLI tool",
      }],
    });
    const spec = convertRoot(config);
    expect(spec.about).toBe("A simple CLI tool");
  });

  it("extracts description as about when no summary", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: {},
        description: "Just a description",
      }],
    });
    const spec = convertRoot(config);
    expect(spec.about).toBe("Just a description");
  });

  it("sets long when both summary and description are present", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: {},
        summary: "Short help",
        description: "This is a much longer description of the app.",
      }],
    });
    const spec = convertRoot(config);
    expect(spec.about).toBe("Short help");
    expect(spec.long).toBe("This is a much longer description of the app.");
  });
});

describe("options", () => {
  it("renders boolean flags", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { verbose: { name: "verbose", type: "boolean", char: "v", description: "Be verbose" } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
    expect(spec.flags[0].short).toBe("v");
    expect(spec.flags[0].arg).toBeNull();
  });

  it("renders option flags with arg", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { output: { name: "output", type: "option", char: "o", description: "Output dir", helpValue: "<DIR>" } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].arg).not.toBeNull();
    expect(spec.flags[0].arg!.name).toBe("DIR");
  });

  it("marks required options", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { env: { name: "env", type: "option", description: "Environment", required: true } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].required).toBe(true);
  });

  it("renders allowNo as negate", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { color: { name: "color", type: "boolean", description: "Enable color", allowNo: true } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].negate).toBe("--color");
  });

  it("renders choices", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { format: { name: "format", type: "option", description: "Output format", options: ["json", "yaml"] } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].arg?.choices?.values).toEqual(["json", "yaml"]);
  });

  it("renders default values for string options", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { format: { name: "format", type: "option", description: "Format", default: "json" } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].default).toEqual(["json"]);
  });

  it("renders boolean default true", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { color: { name: "color", type: "boolean", description: "Enable color", default: true } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].defaultBool).toBe(true);
  });

  it("skips false default for boolean flags", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { force: { name: "force", type: "boolean", description: "Force operation", default: false } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    const forceFlag = spec.flags.find((f) => f.long === "force");
    expect(forceFlag).toBeDefined();
    expect(forceFlag!.default).toEqual([]);
    expect(forceFlag!.defaultBool).toBeNull();
  });

  it("preserves string zero as default", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { port: { name: "port", type: "option", description: "Port number", default: "0" } },
        args: {},
      }],
    });

    const output = generate(config);
    expect(output).toContain(`default="0"`);
  });

  it("renders env variable", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { token: { name: "token", type: "option", description: "Auth token", env: "MYCLI_TOKEN" } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].env).toBe("MYCLI_TOKEN");
  });

  it("hides hidden flags", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { secret: { name: "secret", type: "option", description: "Secret", hidden: true } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].hide).toBe(true);
  });

  it("skips help and version flags", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {
          help: { name: "help", type: "boolean", description: "Show help" },
          version: { name: "version", type: "boolean", description: "Show version" },
          custom: { name: "custom", type: "option", description: "Custom flag" },
        },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("custom");
  });

  it("renders multiple/variadic options", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { include: { name: "include", type: "option", description: "Include patterns", multiple: true } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    const includeFlag = spec.flags.find((f) => f.long === "include");
    expect(includeFlag).toBeDefined();
    expect(includeFlag!.var).toBe(true);
    expect(includeFlag!.arg?.var).toBe(true);
  });

  it("renders deprecated flag with message", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {
          oldFlag: { name: "oldFlag", type: "option", description: "Old flag", deprecated: { message: "Use --new-flag instead" } },
        },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    const oldFlag = spec.flags.find((f) => f.long === "oldFlag");
    expect(oldFlag).toBeDefined();
    expect(oldFlag!.deprecated).toBe("Use --new-flag instead");
  });

  it("renders flag with charAliases", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { verbose: { name: "verbose", type: "boolean", char: "v", charAliases: ["V"], description: "Be verbose" } },
        args: {},
      }],
    });

    const spec = convertRoot(config);
    expect(spec.flags[0].short).toBe("v");
  });
});

describe("arguments", () => {
  it("converts required args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { file: { name: "file", description: "Input file", required: true } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args).toHaveLength(1);
    expect(spec.args[0].name).toBe("file");
    expect(spec.args[0].required).toBe(true);
  });

  it("converts optional args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { filter: { name: "filter", description: "Filter" } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args[0].required).toBe(false);
  });

  it("converts variadic args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { files: { name: "files", description: "Files", multiple: true } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args[0].var).toBe(true);
  });

  it("converts choices on args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { env: { name: "env", description: "Environment", options: ["dev", "prod"] } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args[0].choices?.values).toEqual(["dev", "prod"]);
  });

  it("converts default on args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { output: { name: "output", description: "Output file", default: "out.txt" } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args[0].default).toEqual(["out.txt"]);
  });

  it("converts hidden args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: { internal: { name: "internal", description: "Internal arg", hidden: true } },
      }],
    });

    const spec = convertRoot(config);
    expect(spec.args[0].hide).toBe(true);
  });
});

describe("commands", () => {
  it("renders subcommands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "add", flags: {}, args: {}, description: "Add a file" },
        { id: "remove", flags: {}, args: {}, description: "Remove files" },
      ],
    });

    const output = generate(config);

    expect(output).toContain("cmd add");
    expect(output).toContain("cmd remove");
  });

  it("renders command aliases", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "remove", flags: {}, args: {}, description: "Remove files", aliases: ["rm", "del"] },
      ],
    });

    const spec = convertRoot(config);
    const removeCmd = spec.cmds.find((c) => c.name === "remove");
    expect(removeCmd).toBeDefined();
    expect(removeCmd!.aliases).toContain("rm");
    expect(removeCmd!.aliases).toContain("del");
  });

  it("renders single command alias", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "install", flags: {}, args: {}, description: "Install packages", aliases: ["i"] },
      ],
    });

    const spec = convertRoot(config);
    const installCmd = spec.cmds.find((c) => c.name === "install");
    expect(installCmd).toBeDefined();
    expect(installCmd!.aliases).toContain("i");
  });

  it("handles hidden commands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "secret", flags: {}, args: {}, hidden: true },
      ],
    });

    const spec = convertRoot(config);
    const secretCmd = spec.cmds.find((c) => c.name === "secret");
    expect(secretCmd).toBeDefined();
    expect(secretCmd!.hide).toBe(true);
  });

  it("renders nested command hierarchy from topic separator", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "db:migrate:up", flags: {}, args: {}, description: "Apply migrations" },
        { id: "db:migrate:down", flags: {}, args: {}, description: "Rollback migrations" },
      ],
      topics: [
        { name: "db", description: "Database operations" },
        { name: "db:migrate", description: "Run migrations" },
      ],
    });

    const spec = convertRoot(config);

    const dbCmd = spec.cmds.find((c) => c.name === "db");
    expect(dbCmd).toBeDefined();
    expect(dbCmd!.help).toBe("Database operations");
    expect(dbCmd!.subcommandRequired).toBe(true);

    const migrateCmd = dbCmd!.cmds.find((c) => c.name === "migrate");
    expect(migrateCmd).toBeDefined();
    expect(migrateCmd!.help).toBe("Run migrations");

    expect(migrateCmd!.cmds.find((c) => c.name === "up")).toBeDefined();
    expect(migrateCmd!.cmds.find((c) => c.name === "down")).toBeDefined();
  });

  it("handles deprecated commands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "old-cmd", flags: {}, args: {}, state: "deprecated" },
      ],
    });

    const spec = convertRoot(config);
    const oldCmd = spec.cmds.find((c) => c.name === "old-cmd");
    expect(oldCmd).toBeDefined();
    expect(oldCmd!.deprecated).toBe("deprecated");
  });

  it("renders command with summary and description (long_help)", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "build", flags: {}, args: {}, summary: "Build the project", description: "Detailed build explanation" },
      ],
    });

    const spec = convertRoot(config);
    const buildCmd = spec.cmds.find((c) => c.name === "build");
    expect(buildCmd).toBeDefined();
    expect(buildCmd!.help).toBe("Build the project");
    expect(buildCmd!.helpLong).toBe("Detailed build explanation");
  });

  it("handles command with multiple flags", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "build",
        flags: {
          output: { name: "output", type: "option", char: "o", description: "Output directory" },
          minify: { name: "minify", type: "boolean", description: "Minify output" },
          watch: { name: "watch", type: "boolean", description: "Watch for changes" },
        },
        args: {},
        description: "Build the project",
      }],
    });

    const spec = convertRoot(config);
    const buildCmd = spec.cmds.find((c) => c.name === "build");
    expect(buildCmd).toBeDefined();
    expect(buildCmd!.flags).toHaveLength(3);
    expect(buildCmd!.flags.map((f) => f.long)).toContain("output");
    expect(buildCmd!.flags.map((f) => f.long)).toContain("minify");
    expect(buildCmd!.flags.map((f) => f.long)).toContain("watch");
  });
});

describe("subcommand_required", () => {
  it("sets subcommand_required for topic nodes", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "config:get", flags: {}, args: {}, description: "Get a value" },
        { id: "config:set", flags: {}, args: {}, description: "Set a value" },
      ],
      topics: [
        { name: "config", description: "Manage config" },
      ],
    });

    const spec = convertRoot(config);
    const configCmd = spec.cmds.find((c) => c.name === "config");
    expect(configCmd).toBeDefined();
    expect(configCmd!.subcommandRequired).toBe(true);
  });

  it("does not set subcommand_required for leaf commands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "run", flags: {}, args: {}, description: "Run something" },
      ],
    });

    const spec = convertRoot(config);
    const runCmd = spec.cmds.find((c) => c.name === "run");
    expect(runCmd).toBeDefined();
    expect(runCmd!.subcommandRequired).toBe(false);
  });
});

describe("special character escaping", () => {
  it("handles special chars in flag help", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: { format: { name: "format", type: "option", description: "Output format:\n  json\n  yaml" } },
        args: {},
      }],
    });

    const output = generate(config);
    expect(output).toContain("help=");
    expect(() => validateKDL(output.split("\n").slice(1).join("\n"))).not.toThrow();
  });
});

describe("KDL round-trip validation", () => {
  it("generates valid KDL for basic CLI", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {
          verbose: { name: "verbose", type: "boolean", char: "v", description: "Be verbose" },
          output: { name: "output", type: "option", char: "o", description: "Output dir" },
        },
        args: {},
      }],
    });

    const output = generate(config);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });

  it("generates valid KDL for CLI with nested commands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "db:migrate:up", flags: {}, args: {}, description: "Apply migrations" },
        { id: "db:migrate:down", flags: {}, args: {}, description: "Rollback" },
      ],
      topics: [
        { name: "db", description: "Database ops" },
        { name: "db:migrate", description: "Migrations" },
      ],
    });

    const output = generate(config);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });

  it("generates valid KDL for CLI with flags and args", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {
          format: { name: "format", type: "option", description: "Format", options: ["json", "yaml"], default: "json" },
          verbose: { name: "verbose", type: "boolean", description: "Be verbose", allowNo: true },
        },
        args: { input: { name: "input", description: "Input file", required: true } },
      }],
    });

    const output = generate(config);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });
});

describe("generateKDL", () => {
  it("is an alias for generate", () => {
    const config = makeConfig({ bin: "app" });
    expect(generateKDL(config)).toBe(generate(config));
  });
});

describe("JSON output", () => {
  it("generates JSON output with correct structure", () => {
    const config = makeConfig({
      bin: "mycli",
      version: "2.0.0",
      commands: [
        {
          id: "mycli",
          flags: { verbose: { name: "verbose", type: "boolean", char: "v", description: "Be verbose" } },
          args: {},
          description: "A CLI tool",
        },
        { id: "run", flags: {}, args: {}, description: "Run something" },
      ],
    });

    const json = generateJSON(config);
    const parsed = JSON.parse(json);

    expect(parsed.name).toBe("mycli");
    expect(parsed.bin).toBe("mycli");
    expect(parsed.version).toBe("2.0.0");
    expect(parsed.about).toBe("A CLI tool");
    expect(parsed.flags).toHaveLength(1);
    expect(parsed.cmds).toHaveLength(1);
    expect(parsed.cmds[0].name).toBe("run");
  });

  it("includes choices in JSON output", () => {
    const config = makeConfig({
      bin: "deploy",
      commands: [{
        id: "deploy",
        flags: { env: { name: "env", type: "option", description: "Environment", options: ["dev", "prod"] } },
        args: {},
      }],
    });

    const json = generateJSON(config);
    const parsed = JSON.parse(json);

    expect(parsed.flags[0].arg.choices).toEqual(["dev", "prod"]);
  });

  it("includes flag details in JSON", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {
          env: { name: "env", type: "option", description: "Environment", required: true },
          color: { name: "color", type: "boolean", description: "Enable color", allowNo: true },
        },
        args: {},
      }],
    });

    const json = generateJSON(config);
    const parsed = JSON.parse(json);

    expect(parsed.flags).toHaveLength(2);
    const envFlag = parsed.flags.find((f: { name: string }) => f.name === "--env");
    expect(envFlag.required).toBe(true);

    const colorFlag = parsed.flags.find((f: { name: string }) => f.name === "--color");
    expect(colorFlag.negate).toBe("--color");
  });

  it("includes args in JSON output", () => {
    const config = makeConfig({
      bin: "app",
      commands: [{
        id: "app",
        flags: {},
        args: {
          file: { name: "file", description: "Input file", required: true },
          output: { name: "output", description: "Output file" },
        },
      }],
    });

    const json = generateJSON(config);
    const parsed = JSON.parse(json);

    expect(parsed.args).toHaveLength(2);
    expect(parsed.args[0].name).toBe("file");
    // JSON renderer: required:true is omitted (default), required:false is explicit
    expect(parsed.args[0].required).toBeUndefined();
    expect(parsed.args[1].name).toBe("output");
    expect(parsed.args[1].required).toBe(false);
  });
});

describe("convertRoot", () => {
  it("returns a spec with correct structure", () => {
    const config = makeConfig({
      bin: "mycli",
      version: "2.0.0",
      commands: [{
        id: "mycli",
        flags: { verbose: { name: "verbose", type: "boolean", description: "Be verbose" } },
        args: {},
        description: "A CLI tool",
      }],
    });

    const spec = convertRoot(config);

    expect(spec.name).toBe("mycli");
    expect(spec.bin).toBe("mycli");
    expect(spec.version).toBe("2.0.0");
    expect(spec.about).toBe("A CLI tool");
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
  });

  it("includes args from root command in spec", () => {
    const config = makeConfig({
      bin: "cmd",
      commands: [{
        id: "cmd",
        flags: {},
        args: {
          file: { name: "file", description: "Input file", required: true },
          output: { name: "output", description: "Output file" },
        },
      }],
    });

    const spec = convertRoot(config);

    expect(spec.args).toHaveLength(2);
    expect(spec.args[0].name).toBe("file");
    expect(spec.args[0].required).toBe(true);
    expect(spec.args[1].name).toBe("output");
    expect(spec.args[1].required).toBe(false);
  });
});

describe("edge cases", () => {
  it("handles empty CLI with no options or args", () => {
    const config = makeConfig({ bin: "empty" });
    const output = generate(config);

    expect(output).toContain("name empty");
    expect(output).toContain("bin empty");
    expect(output).not.toMatch(/\bflag\b/);
    expect(output).not.toMatch(/^(\s*)arg /m);
    expect(output).not.toMatch(/\bcmd\b/);
  });

  it("handles CLI with only subcommands", () => {
    const config = makeConfig({
      bin: "app",
      commands: [
        { id: "start", flags: {}, args: {}, description: "Start" },
        { id: "stop", flags: {}, args: {}, description: "Stop" },
      ],
    });

    const output = generate(config);

    expect(output).toContain("cmd start");
    expect(output).toContain("cmd stop");
  });

  it("handles deeply nested command structure", () => {
    const config = makeConfig({
      bin: "myapp",
      version: "1.0.0",
      commands: [
        { id: "db:migrate:up", flags: {}, args: {}, description: "Apply migrations" },
        { id: "db:migrate:down", flags: {}, args: {}, description: "Rollback migrations" },
      ],
      topics: [
        { name: "db", description: "Database operations" },
        { name: "db:migrate", description: "Run migrations" },
      ],
    });

    const output = generate(config);

    expect(output).toContain("cmd db");
    expect(output).toContain("Database operations");
    expect(output).toContain("cmd migrate");
    expect(output).toContain("migrate");
  });

  it("excludes root command from subcommand tree", () => {
    const config = makeConfig({
      bin: "mycli",
      commands: [
        {
          id: "mycli",
          flags: { verbose: { name: "verbose", type: "boolean", description: "Be verbose" } },
          args: {},
          description: "The CLI itself",
        },
        { id: "run", flags: {}, args: {}, description: "Run something" },
      ],
    });

    const spec = convertRoot(config);

    // Root command flags should be at top level
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
    // Only "run" should appear as a subcommand, not "mycli"
    expect(spec.cmds).toHaveLength(1);
    expect(spec.cmds[0].name).toBe("run");
  });
});

describe("full output format", () => {
  it("matches expected KDL output for a complete example", () => {
    const config = makeConfig({
      bin: "example",
      version: "1.0.0",
      commands: [{
        id: "example",
        flags: {
          file: { name: "file", type: "option", char: "f", description: "Some input file" },
          verbose: { name: "verbose", type: "boolean", description: "Enable verbose output" },
        },
        args: {},
        description: "An example CLI",
      }],
    });

    const output = generate(config);

    expect(output).toContain("name example");
    expect(output).toContain("bin example");
    expect(output).toContain(`version "1.0.0"`);
    expect(output).toContain(`about "An example CLI"`);
    expect(output).toContain("file");
    expect(output).toContain("verbose");
  });
});
