import { convertRoot } from "./convert.js";
import type { OclifConfig } from "./convert.js";
import { renderKDL, renderJSON, generate as coreGenerate } from "@usage-spec/core";
import type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices } from "@usage-spec/core";

export { convertRoot } from "./convert.js";
export type { OclifConfig, OclifCommand, OclifFlag, OclifArg, OclifTopic } from "./convert.js";
export { renderKDL } from "@usage-spec/core";
export type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices };

/**
 * Generates a usage spec in KDL format from an oclif Config.
 */
export function generate(config: OclifConfig): string {
  const spec = convertRoot(config);
  return coreGenerate(spec, {
    format: "kdl",
    comment: "@generated by @usage-spec/oclif from oclif metadata",
  });
}

/**
 * Generates a usage spec in KDL format from an oclif Config.
 */
export function generateKDL(config: OclifConfig): string {
  return generate(config);
}

/**
 * Generates a usage spec in JSON format from an oclif Config.
 */
export function generateJSON(config: OclifConfig): string {
  const spec = convertRoot(config);
  return coreGenerate(spec, { format: "json" });
}
