package cliusage

import (
	"encoding/json"
	"testing"

	cli "github.com/urfave/cli/v2"
	"github.com/stretchr/testify/assert"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func TestSimpleCommand_BasicCLI(t *testing.T) {
	app := &cli.App{
		Name:    "mycli",
		Version: "1.0.0",
		Usage:   "A CLI tool",
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Enable verbose output"},
			&cli.StringFlag{Name: "config", Aliases: []string{"c"}, Usage: "Config file path"},
		},
	}

	output := GenerateKDL(app)

	assert.Contains(t, output, "name mycli")
	assert.Contains(t, output, "bin mycli")
	assert.Contains(t, output, `"1.0.0"`)
	assert.Contains(t, output, "verbose")
	assert.Contains(t, output, "config")
}

func TestSimpleCommand_GeneratedComment(t *testing.T) {
	app := &cli.App{Name: "app"}
	output := GenerateKDL(app)
	assert.Contains(t, output, "// @generated by urfavecli-usage from urfave/cli metadata")
}

func TestSimpleCommand_CustomBin(t *testing.T) {
	app := &cli.App{Name: "app"}
	output := GenerateKDL(app, "my-app")
	assert.Contains(t, output, "bin my-app")
}

func TestVersion_ExtractsVersion(t *testing.T) {
	app := &cli.App{Name: "app", Version: "2.0.0"}
	spec := Convert(app)
	assert.Equal(t, "2.0.0", spec.Version)
}

func TestVersion_SkipsWhenNotSet(t *testing.T) {
	app := &cli.App{Name: "app"}
	output := GenerateKDL(app)
	assert.NotContains(t, output, "version ")
}

func TestAbout_ExtractsUsage(t *testing.T) {
	app := &cli.App{Name: "app", Usage: "A simple CLI tool"}
	spec := Convert(app)
	assert.Equal(t, "A simple CLI tool", spec.About)
}

func TestAbout_SetsLongFromDescription(t *testing.T) {
	app := &cli.App{Name: "app", Usage: "Short", Description: "Detailed description"}
	spec := Convert(app)
	assert.Equal(t, "Short", spec.About)
	assert.Equal(t, "Detailed description", spec.Long)
}

func TestNestedSubcommands_Recursive(t *testing.T) {
	app := &cli.App{
		Name:  "app",
		Usage: "An app",
		Commands: []*cli.Command{
			{
				Name: "db", Usage: "Database ops",
				Subcommands: []*cli.Command{
					{Name: "migrate", Usage: "Run migrations"},
				},
			},
		},
	}

	output := GenerateKDL(app)

	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, `"Database ops"`)
	assert.Contains(t, output, "cmd migrate")
}

func TestNestedSubcommands_DeepNesting(t *testing.T) {
	app := &cli.App{
		Name:    "myapp",
		Version: "1.0.0",
		Usage:   "My application",
		Commands: []*cli.Command{
			{
				Name: "db", Usage: "Database operations",
				Subcommands: []*cli.Command{
					{
						Name: "migrate", Usage: "Run migrations",
						Subcommands: []*cli.Command{
							{Name: "up", Usage: "Apply migrations"},
							{Name: "down", Usage: "Rollback migrations"},
						},
					},
				},
			},
		},
	}

	output := GenerateKDL(app)

	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, "cmd migrate")
	assert.Contains(t, output, "cmd up")
	assert.Contains(t, output, "cmd down")
}

func TestOptions_ShortAndLong(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Be verbose"},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, `flag "-v --verbose"`)
}

func TestOptions_RequiredFlag(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "env", Usage: "Target environment", Required: true},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, "required=#true")
}

func TestOptions_DefaultString(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "format", Usage: "Output format", Value: "json"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "format")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"json"}, flag.Default)
}

func TestOptions_DefaultNumberAsString(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.IntFlag{Name: "retries", Usage: "Number of retries", Value: 3},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "retries")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"3"}, flag.Default)
}

func TestOptions_BoolDefaultTrue(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "color", Usage: "Enable color", Value: true},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "color")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.DefaultBool)
	assert.True(t, *flag.DefaultBool)
}

func TestOptions_SkipsBoolDefaultFalse(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "force", Usage: "Force the operation"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.DefaultBool)
	assert.Nil(t, flag.Default)
}

func TestOptions_DefaultStringZero(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "port", Usage: "Port number", Value: "0"},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, `default="0"`)
}

func TestOptions_HiddenOption(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "secret", Usage: "Secret option", Hidden: true},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "secret")
	assert.NotNil(t, flag)
	assert.True(t, flag.Hide)
}

func TestOptions_StringSlice(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringSliceFlag{Name: "include", Usage: "Include patterns"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "include")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
	assert.NotNil(t, flag.Arg)
	assert.True(t, flag.Arg.Var)
}

func TestOptions_IntSlice(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.IntSliceFlag{Name: "ports", Usage: "Port numbers"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "ports")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
}

func TestBooleanFlag_NoArg(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "force", Usage: "Force the operation"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.Arg)
}

func TestBooleanFlag_WithShort(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "force", Aliases: []string{"f"}, Usage: "Force the operation"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Equal(t, "f", flag.Short)
	assert.Equal(t, "force", flag.Long)
}

func TestEnvVars_EnvSet(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "token", Usage: "Auth token", EnvVars: []string{"MYCLI_TOKEN"}},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "token")
	assert.NotNil(t, flag)
	assert.Equal(t, "MYCLI_TOKEN", flag.Env)
}

func TestEnvVars_NotSet(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "token", Usage: "Auth token"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "token")
	assert.NotNil(t, flag)
	assert.Equal(t, "", flag.Env)
}

func TestCountFlag(t *testing.T) {
	count := 0
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Verbosity level", Count: &count},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "verbose")
	assert.NotNil(t, flag)
	assert.True(t, flag.Count)
}

func TestSkipsBuiltinFlags_HelpVersion(t *testing.T) {
	app := &cli.App{
		Name:    "app",
		Version: "1.0.0",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "custom", Usage: "A custom flag"},
		},
	}

	spec := Convert(app)
	flagNames := collectFlagNames(spec.Flags)
	assert.NotContains(t, flagNames, "help")
	assert.NotContains(t, flagNames, "version")
	assert.Contains(t, flagNames, "custom")
}

func TestCommands_Subcommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "add", Usage: "Add a file"},
			{Name: "remove", Usage: "Remove files"},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, "cmd add")
	assert.Contains(t, output, "cmd remove")
}

func TestCommands_Aliases(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "install", Aliases: []string{"i", "add"}, Usage: "Install packages"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "install")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "i")
	assert.Contains(t, cmd.Aliases, "add")
}

func TestCommands_SingleAlias(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "remove", Aliases: []string{"rm"}, Usage: "Remove packages"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "remove")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "rm")
}

func TestCommands_HiddenCommand(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "secret", Hidden: true},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "secret")
	assert.NotNil(t, cmd)
	assert.True(t, cmd.Hide)
}

func TestCommands_NestedSubcommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name: "db", Usage: "Database ops",
				Subcommands: []*cli.Command{
					{Name: "migrate", Usage: "Run migrations"},
				},
			},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, "cmd migrate")
}

func TestCommands_MultipleFlagsOnSubcommand(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name: "build", Usage: "Build the project",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "output", Aliases: []string{"o"}, Usage: "Output directory"},
					&cli.BoolFlag{Name: "minify", Usage: "Minify output"},
					&cli.BoolFlag{Name: "watch", Usage: "Watch for changes"},
				},
			},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "build")
	assert.NotNil(t, cmd)
	assert.Equal(t, 3, len(cmd.Flags))
	flagNames := collectFlagNames(cmd.Flags)
	assert.Contains(t, flagNames, "output")
	assert.Contains(t, flagNames, "minify")
	assert.Contains(t, flagNames, "watch")
}

func TestPositionalArgs_FromArgsUsage(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "add", Usage: "Add a file", ArgsUsage: "<file>"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "file", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
}

func TestPositionalArgs_Optional(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "list", Usage: "List items", ArgsUsage: "[filter]"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "list")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "filter", cmd.Args[0].Name)
	assert.False(t, cmd.Args[0].Required)
}

func TestPositionalArgs_Variadic(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "add", Usage: "Add files", ArgsUsage: "<files...>"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "files", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Var)
}

func TestPositionalArgs_Mixed(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "copy", Usage: "Copy files", ArgsUsage: "<source> [dest]"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "copy")
	assert.NotNil(t, cmd)
	assert.Equal(t, 2, len(cmd.Args))
	assert.Equal(t, "source", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
	assert.Equal(t, "dest", cmd.Args[1].Name)
	assert.False(t, cmd.Args[1].Required)
}

func TestLongHelp_Description(t *testing.T) {
	app := &cli.App{
		Usage:       "Short help",
		Description: "This is a much longer description of the app.",
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, `"Short help"`)
	assert.Contains(t, output, `"This is a much longer description of the app."`)
}

func TestSpecialCharEscaping_Help(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "format", Usage: "Output format:\n  json\n  yaml"},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, "help=")
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_BasicCLI(t *testing.T) {
	app := &cli.App{
		Name:    "app",
		Version: "1.0.0",
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Be verbose"},
			&cli.StringFlag{Name: "file", Aliases: []string{"f"}, Usage: "Input file"},
		},
	}

	output := GenerateKDL(app)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_WithCommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "add", Usage: "Add a file", ArgsUsage: "<file>"},
			{Name: "remove", Usage: "Remove files"},
		},
	}

	output := GenerateKDL(app)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_NestedCommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name: "config", Usage: "Config",
				Subcommands: []*cli.Command{
					{Name: "get", Usage: "Get value"},
				},
			},
		},
	}

	output := GenerateKDL(app)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestGenerateKDL_IsAlias(t *testing.T) {
	app := &cli.App{Name: "app", Usage: "A CLI"}
	kdl := GenerateKDL(app)
	spec := Convert(app)
	assert.Equal(t, usagespec.Generate(spec, "kdl", "@generated by urfavecli-usage from urfave/cli metadata"), kdl)
}

func TestJSONOutput_CorrectStructure(t *testing.T) {
	app := &cli.App{
		Name:    "mycli",
		Version: "2.0.0",
		Usage:   "A CLI tool",
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Be verbose"},
		},
		Commands: []*cli.Command{
			{Name: "run", Usage: "Run something"},
		},
	}

	jsonStr := GenerateJSON(app)
	var parsed map[string]interface{}
	err := json.Unmarshal([]byte(jsonStr), &parsed)
	assert.NoError(t, err)
	assert.Equal(t, "mycli", parsed["name"])
	assert.Equal(t, "mycli", parsed["bin"])
	assert.Equal(t, "2.0.0", parsed["version"])
	assert.Equal(t, "A CLI tool", parsed["about"])
}

func TestJSONOutput_FlagDetails(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "env", Usage: "Target environment", Required: true},
		},
	}

	jsonStr := GenerateJSON(app)
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	flags := parsed["flags"].([]interface{})
	assert.Equal(t, 1, len(flags))
	flag := flags[0].(map[string]interface{})
	assert.Equal(t, true, flag["required"])
}

func TestJSONOutput_CustomBin(t *testing.T) {
	app := &cli.App{Name: "app", Usage: "A tool"}
	jsonStr := GenerateJSON(app, "my-tool")
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	assert.Equal(t, "my-tool", parsed["bin"])
}

func TestConvertRoot_CorrectStructure(t *testing.T) {
	app := &cli.App{
		Name:    "mycli",
		Version: "2.0.0",
		Usage:   "A CLI tool",
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Usage: "Be verbose"},
		},
	}

	spec := ConvertRoot(app)

	assert.Equal(t, "mycli", spec.Name)
	assert.Equal(t, "mycli", spec.Bin)
	assert.Equal(t, "2.0.0", spec.Version)
	assert.Equal(t, "A CLI tool", spec.About)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "verbose", spec.Flags[0].Long)
	assert.Equal(t, "v", spec.Flags[0].Short)
}

func TestConvertRoot_ArgsFromCommand(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "add", Usage: "Add a file", ArgsUsage: "<file>"},
		},
	}

	spec := ConvertRoot(app)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "file", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
}

func TestEdgeCases_EmptyCLI(t *testing.T) {
	app := &cli.App{Name: "empty"}
	output := GenerateKDL(app)

	assert.Contains(t, output, "name empty")
	assert.Contains(t, output, "bin empty")
}

func TestEdgeCases_OnlySubcommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "start", Usage: "Start"},
			{Name: "stop", Usage: "Stop"},
		},
	}

	output := GenerateKDL(app)
	assert.Contains(t, output, "cmd start")
	assert.Contains(t, output, "cmd stop")
}

func TestEdgeCases_FlagWithOnlyLong(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{Name: "verbose", Usage: "Be verbose"},
		},
	}

	spec := Convert(app)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "verbose", spec.Flags[0].Long)
	assert.Equal(t, "", spec.Flags[0].Short)
}

func TestFullOutput_CompleteExample(t *testing.T) {
	app := &cli.App{
		Name:    "example",
		Version: "1.0.0",
		Usage:   "An example CLI",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "file", Aliases: []string{"f"}, Usage: "Some input file"},
			&cli.BoolFlag{Name: "verbose", Usage: "Enable verbose output"},
		},
	}

	output := GenerateKDL(app, "example")

	assert.Contains(t, output, "name example")
	assert.Contains(t, output, "bin example")
	assert.Contains(t, output, `"1.0.0"`)
	assert.Contains(t, output, `"An example CLI"`)
}

func TestSubcommandRequired(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name: "db",
				Subcommands: []*cli.Command{
					{Name: "migrate", Usage: "Migrate"},
				},
			},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "db")
	assert.NotNil(t, cmd)
	assert.True(t, cmd.SubcommandRequired)
}

func TestCommandDescription(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{Name: "deploy", Usage: "Deploy", Description: "Deploy the application to the cloud"},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "deploy")
	assert.NotNil(t, cmd)
	assert.Equal(t, "Deploy", cmd.Help)
	assert.Equal(t, "Deploy the application to the cloud", cmd.HelpLong)
}

func TestIntFlag_Default(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.IntFlag{Name: "port", Usage: "Port number", Value: 8080},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "port")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"8080"}, flag.Default)
	assert.NotNil(t, flag.Arg)
}

func TestFlagArgName_Uppercase(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "output-dir", Usage: "Output directory"},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "output-dir")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.Arg)
	assert.Equal(t, "OUTPUT_DIR", flag.Arg.Name)
}

func TestRootPositionalArgs(t *testing.T) {
	app := &cli.App{
		Name:     "myapp",
		ArgsUsage: "<input>",
	}

	spec := Convert(app)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, "input", spec.Args[0].Name)
	assert.True(t, spec.Args[0].Required)
}

func TestFloat64Flag(t *testing.T) {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.Float64Flag{Name: "rate", Usage: "Rate", Value: 0.5},
		},
	}

	spec := Convert(app)
	flag := findFlag(spec.Flags, "rate")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.Arg)
}

func TestCommandWithFlagsAndSubcommands(t *testing.T) {
	app := &cli.App{
		Commands: []*cli.Command{
			{
				Name: "db", Usage: "Database ops",
				Flags: []cli.Flag{
					&cli.BoolFlag{Name: "dry-run", Usage: "Dry run mode"},
				},
				Subcommands: []*cli.Command{
					{Name: "migrate", Usage: "Migrate"},
				},
			},
		},
	}

	spec := Convert(app)
	cmd := findCmd(spec.Cmds, "db")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Flags))
	assert.Equal(t, "dry-run", cmd.Flags[0].Long)
	assert.Equal(t, 1, len(cmd.Cmds))
}

func findFlag(flags []usagespec.SpecFlag, name string) *usagespec.SpecFlag {
	for i := range flags {
		if flags[i].Long == name {
			return &flags[i]
		}
	}
	return nil
}

func findCmd(cmds []usagespec.SpecCommand, name string) *usagespec.SpecCommand {
	for i := range cmds {
		if cmds[i].Name == name {
			return &cmds[i]
		}
	}
	return nil
}

func collectFlagNames(flags []usagespec.SpecFlag) []string {
	names := make([]string, len(flags))
	for i, f := range flags {
		names[i] = f.Long
	}
	return names
}
