package cliusage

import (
	cli "github.com/urfave/cli/v2"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func Generate(app *cli.App, format string, comment string) string {
	spec := Convert(app)
	return usagespec.Generate(spec, format, comment)
}

func GenerateKDL(app *cli.App, bin ...string) string {
	spec := Convert(app)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "kdl", "@generated by urfavecli-usage from urfave/cli metadata")
}

func GenerateJSON(app *cli.App, bin ...string) string {
	spec := Convert(app)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "json", "")
}

func ConvertRoot(app *cli.App) usagespec.Spec {
	return Convert(app)
}
