import { describe, it, expect } from "vitest";
import { Command, Option, Argument } from "commander";
import { generate, generateJSON, generateKDL, convertRoot, renderKDL } from "../src/index.js";
import { validateKDL } from "@usage-spec/core";

describe("simple command", () => {
  it("generates spec for a basic CLI with version and options", () => {
    const cmd = new Command("mycli")
      .version("1.0.0")
      .description("A simple CLI")
      .option("-v, --verbose", "Enable verbose output")
      .option("-c, --config <PATH>", "Config file path");

    const output = generate(cmd);

    expect(output).toContain("name mycli");
    expect(output).toContain("bin mycli");
    expect(output).toContain(`version "1.0.0"`);
    expect(output).toContain(`about "A simple CLI"`);
    expect(output).toContain(`flag "-v --verbose" help="Enable verbose output"`);
    expect(output).toContain(`flag "-c --config" help="Config file path"`);
  });

  it("includes generated comment header", () => {
    const cmd = new Command("app");
    const output = generate(cmd);
    expect(output).toContain("// @generated by @usage-spec/commander from Commander.js metadata");
  });

  it("uses custom bin name when provided", () => {
    const cmd = new Command("app");
    const output = generate(cmd, "my-app");
    expect(output).toContain("bin my-app");
  });
});

describe("nested subcommands", () => {
  it("renders subcommands recursively", () => {
    const root = new Command("app").description("An app");
    const sub = new Command("sub").description("A subcommand");
    const nested = new Command("nested").description("A nested command");
    sub.addCommand(nested);
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain("cmd sub");
    expect(output).toContain(`help="A subcommand"`);
    expect(output).toContain("cmd nested");
    expect(output).toContain(`help="A nested command"`);
  });
});

describe("global/persistent flags", () => {
  it("does not mark root-level flags as global", () => {
    const root = new Command("app").option("-d, --debug", "Enable debug mode");
    const sub = new Command("run").description("Run something");
    root.addCommand(sub);

    const output = generate(root);

    // Commander.js doesn't have persistent flags like Cobra;
    // flags on root are just root-level flags (not global)
    expect(output).toContain(`flag "-d --debug" help="Enable debug mode"`);
  });
});

describe("required options", () => {
  it("marks mandatory options as required", () => {
    const cmd = new Command("deploy").requiredOption("--env <ENV>", "Target environment");

    const output = generate(cmd);

    expect(output).toContain(`flag --env help="Target environment" required=#true`);
  });
});

describe("hidden and deprecated", () => {
  it("hides commands and options", () => {
    const root = new Command("app");
    const hiddenCmd = new Command("internal").description("Internal command");
    hiddenCmd._hidden = true;
    root.addCommand(hiddenCmd);

    const opt = new Option("--secret <VAL>", "Secret flag");
    opt.hideHelp();
    root.addOption(opt);

    const output = generate(root);

    expect(output).toContain("cmd internal hide=#true");
    expect(output).toContain(`flag --secret help="Secret flag" hide=#true`);
  });
});

describe("argument inference", () => {
  it("converts required arguments", () => {
    const cmd = new Command("cmd").argument("<file>", "Input file");

    const output = generate(cmd);

    expect(output).toContain("arg <file>");
    expect(output).toContain(`help="Input file"`);
  });

  it("converts optional arguments", () => {
    const cmd = new Command("cmd").argument("[name]", "Optional name");

    const output = generate(cmd);

    expect(output).toContain(`arg "[name]"`);
    expect(output).toContain("required=#false");
  });

  it("converts variadic arguments", () => {
    const cmd = new Command("cmd").argument("<files...>", "Multiple files");

    const output = generate(cmd);

    expect(output).toContain("arg <files>\u2026");
    expect(output).toContain("var=#true");
  });

  it("converts mixed required and optional args", () => {
    const cmd = new Command("cmd")
      .argument("<source>", "Source path")
      .argument("[dest]", "Destination path");

    const output = generate(cmd);

    expect(output).toContain("arg <source>");
    expect(output).toContain(`arg "[dest]"`);
    expect(output).toContain("required=#false");
  });
});

describe("choices", () => {
  it("renders choices for option arguments", () => {
    const cmd = new Command("deploy").addOption(
      new Option("--format <TYPE>", "Output format").choices(["json", "yaml", "toml"])
    );

    const output = generate(cmd);

    expect(output).toContain("choices");
    expect(output).toContain("json");
    expect(output).toContain("yaml");
    expect(output).toContain("toml");
  });

  it("renders choices for positional arguments", () => {
    const cmd = new Command("deploy").addArgument(
      new Argument("<env>", "Environment").choices(["dev", "staging", "prod"])
    );

    const output = generate(cmd);

    expect(output).toContain("arg <env>");
    expect(output).toContain("choices");
    expect(output).toContain("dev");
    expect(output).toContain("staging");
    expect(output).toContain("prod");
  });
});

describe("default values", () => {
  it("renders default value for option", () => {
    const cmd = new Command("app")
      .option("--output <FORMAT>", "Output format", "json")
      .option("--retries <N>", "Number of retries", "3");

    const output = generate(cmd);

    expect(output).toContain(`flag --output help="Output format" default=json`);
    expect(output).toContain(`flag --retries help="Number of retries" default="3"`);
  });

  it("renders default value for argument", () => {
    const cmd = new Command("app").argument("[file]", "Input file", "input.txt");

    const output = generate(cmd);

    expect(output).toContain("default=input.txt");
  });

  it("skips false default for boolean flags", () => {
    const cmd = new Command("app").option("--force", "Force the operation", false);

    const output = generate(cmd);

    const forceLine = output.split("\n").find((l) => l.includes("flag --force"));
    expect(forceLine).toBeDefined();
    expect(forceLine).not.toContain("default");
  });

  it("preserves string zero as default", () => {
    const cmd = new Command("app").option("--port <PORT>", "Port number", "0");

    const output = generate(cmd);

    expect(output).toContain(`default="0"`);
  });

  it("preserves true default for boolean flags", () => {
    const cmd = new Command("app").addOption(
      new Option("--color", "Enable color").default(true)
    );

    const output = generate(cmd);

    expect(output).toContain(`flag --color help="Enable color" default=#true`);
  });
});

describe("boolean flags", () => {
  it("does not render arg for boolean flags", () => {
    const cmd = new Command("app").option("--force", "Force the operation");

    const output = generate(cmd);

    const forceLine = output.split("\n").find((l) => l.includes("flag --force"));
    expect(forceLine).toBeDefined();
    expect(forceLine).not.toContain("arg");
  });
});

describe("skips builtin commands", () => {
  it("does not render the help subcommand", () => {
    const root = new Command("app").addCommand(new Command("run").description("Run"));

    const output = generate(root);

    expect(output).toContain("cmd run");
  });
});

describe("skips builtin flags", () => {
  it("does not render --help and --version flags", () => {
    const cmd = new Command("app").version("1.0.0").option("--custom <VAL>", "A custom flag");

    const output = generate(cmd);

    expect(output).not.toContain("flag --help");
    expect(output).not.toContain("flag --version");
    expect(output).toContain("flag --custom");
  });
});

describe("subcommand_required", () => {
  it("sets subcommand_required for non-runnable commands with subcommands", () => {
    const root = new Command("app");
    const sub = new Command("config").description("Manage config");
    sub.addCommand(new Command("get").description("Get a value"));
    sub.addCommand(new Command("set").description("Set a value"));
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain("subcommand_required=#true");
  });

  it("does not set subcommand_required for runnable commands", () => {
    const root = new Command("app");
    const sub = new Command("task").description("Run a task").action(() => {});
    sub.addCommand(new Command("list").description("List tasks"));
    root.addCommand(sub);

    const output = generate(root);

    const taskLine = output.split("\n").find((l) => l.includes("cmd task"));
    expect(taskLine).toBeDefined();
    expect(taskLine).not.toContain("subcommand_required");
  });

  it("does not set subcommand_required when command has positional args", () => {
    const root = new Command("app");
    const sub = new Command("greet").argument("<name>", "Name to greet");
    sub.addCommand(new Command("formally").description("Formal greeting"));
    root.addCommand(sub);

    const output = generate(root);

    const greetLine = output.split("\n").find((l) => l.includes("cmd greet"));
    expect(greetLine).toBeDefined();
    expect(greetLine).not.toContain("subcommand_required");
  });
});

describe("aliases", () => {
  it("renders command aliases", () => {
    const root = new Command("app");
    const sub = new Command("install").description("Install packages").alias("i").alias("add");
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain("alias i add");
  });

  it("renders single alias", () => {
    const root = new Command("app");
    const sub = new Command("remove").description("Remove packages").alias("rm");
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain("alias rm");
  });
});

describe("long help", () => {
  it("renders long_about for root command with summary + description", () => {
    const root = new Command("app")
      .summary("Short help")
      .description("This is a much longer description of the app.");

    const output = generate(root);

    expect(output).toContain(`about "Short help"`);
    expect(output).toContain(`long_about "This is a much longer description of the app."`);
  });

  it("uses description as about when no summary", () => {
    const cmd = new Command("app").description("Just a description");

    const output = generate(cmd);

    expect(output).toContain(`about "Just a description"`);
    expect(output).not.toContain("long_about");
  });

  it("renders long_help for subcommand", () => {
    const root = new Command("app");
    const sub = new Command("sub").summary("Brief").description("Detailed explanation");
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain("help=Brief");
    expect(output).toContain(`long_help "Detailed explanation"`);  });
});

describe("negated options", () => {
  it("renders negate for --no- options", () => {
    const cmd = new Command("app").option("--no-color", "Disable color output");

    const output = generate(cmd);

    expect(output).toContain("negate=--color");
  });

  it("negated boolean options do not have arg", () => {
    const cmd = new Command("app").option("--no-color", "Disable color output");

    const spec = convertRoot(cmd);
    const colorFlag = spec.flags.find((f) => f.long === "no-color");
    expect(colorFlag).toBeDefined();
    expect(colorFlag!.negate).toBe("--color");
    // --no-color is boolean (no arg), negate flag
    expect(colorFlag!.arg).toBeNull();
  });
});

describe("environment variables", () => {
  it("renders env for options with env vars", () => {
    const cmd = new Command("app").addOption(
      new Option("--color <BOOL>", "Color output").env("MYCLI_COLOR")
    );

    const output = generate(cmd);

    expect(output).toContain("env=MYCLI_COLOR");
  });
});

describe("special character escaping", () => {
  it("handles newlines in command help", () => {
    const root = new Command("app")
      .summary("Short help")
      .description("First line.\nSecond line.\n\nThird paragraph.");

    const output = generate(root);

    expect(output).toContain("long_about");
    // Verify the output is valid KDL
    expect(() => validateKDL(output.split("\n").slice(1).join("\n"))).not.toThrow();
  });

  it("handles special chars in flag help", () => {
    const cmd = new Command("app").option(
      "--format <TYPE>",
      "Output format:\n  json\n  yaml"
    );

    const output = generate(cmd);

    expect(output).toContain("help=");
    // Verify the output is valid KDL
    expect(() => validateKDL(output.split("\n").slice(1).join("\n"))).not.toThrow();
  });
});

describe("KDL round-trip validation", () => {
  it("generates valid KDL for basic command", () => {
    const cmd = new Command("app")
      .version("1.0.0")
      .description("A CLI")
      .option("-v, --verbose", "Be verbose")
      .option("-f, --file <FILE>", "Input file");

    const output = generate(cmd);
    const kdlContent = output.split("\n").slice(1).join("\n");

    expect(() => validateKDL(kdlContent)).not.toThrow();
  });

  it("generates valid KDL for nested commands", () => {
    const root = new Command("app");
    const sub = new Command("config").description("Config");
    sub.addCommand(new Command("get").description("Get value"));
    root.addCommand(sub);

    const output = generate(root);
    const kdlContent = output.split("\n").slice(1).join("\n");

    expect(() => validateKDL(kdlContent)).not.toThrow();
  });
});

describe("generateKDL", () => {
  it("is an alias for generate", () => {
    const cmd = new Command("app").description("A CLI");
    expect(generateKDL(cmd)).toBe(generate(cmd));
  });
});

describe("convertRoot", () => {
  it("returns a spec with correct structure", () => {
    const cmd = new Command("mycli")
      .version("2.0.0")
      .description("A CLI tool")
      .option("--verbose", "Be verbose");

    const spec = convertRoot(cmd);

    expect(spec.name).toBe("mycli");
    expect(spec.bin).toBe("mycli");
    expect(spec.version).toBe("2.0.0");
    expect(spec.about).toBe("A CLI tool");
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
  });

  it("includes arguments in spec", () => {
    const cmd = new Command("cmd")
      .argument("<file>", "Input file")
      .argument("[output]", "Output file");

    const spec = convertRoot(cmd);

    expect(spec.args).toHaveLength(2);
    expect(spec.args[0].name).toBe("file");
    expect(spec.args[0].required).toBe(true);
    expect(spec.args[1].name).toBe("output");
    expect(spec.args[1].required).toBe(false);
  });
});

describe("option with only short flag", () => {
  it("renders short-only flags", () => {
    const cmd = new Command("app").option("-v", "Be verbose");

    const output = generate(cmd);

    expect(output).toContain(`flag -v help="Be verbose"`);
  });
});

describe("option with only long flag", () => {
  it("renders long-only flags", () => {
    const cmd = new Command("app").option("--verbose", "Be verbose");

    const output = generate(cmd);

    expect(output).toContain(`flag --verbose help="Be verbose"`);
  });
});

describe("optional option-argument", () => {
  it("renders flag with optional argument", () => {
    const cmd = new Command("app").option("-c, --cheese [TYPE]", "Add cheese");

    const output = generate(cmd);

    expect(output).toContain(`flag "-c --cheese"`);
    const spec = convertRoot(cmd);
    expect(spec.flags[0].arg?.required).toBe(false);
  });
});

describe("full output format", () => {
  it("matches expected KDL output for a complete example", () => {
    const cmd = new Command("example")
      .version("1.0.0")
      .description("An example CLI")
      .option("-f, --file <FILE>", "Some input file")
      .option("--verbose", "Enable verbose output");

    const output = generate(cmd, "example");

    expect(output).toContain("name example");
    expect(output).toContain("bin example");
    expect(output).toContain(`version "1.0.0"`);
    expect(output).toContain(`about "An example CLI"`);
    expect(output).toContain(`flag "-f --file" help="Some input file"`);
    expect(output).toContain(`flag --verbose help="Enable verbose output"`);
  });

  it("generates complete KDL output matching clap_usage snapshot style", () => {
    const cmd = new Command("example")
      .option("-f, --file <FILE>", "some input file")
      .option("--usage");

    const output = generate(cmd, "example");

    // Should match the style of clap_usage snapshot:
    // name example
    // bin example
    // flag "-f --file" help="some input file" {
    //     arg <FILE>
    // }
    // flag --usage
    const lines = output.split("\n").filter((l) => !l.startsWith("//"));
    expect(lines).toContain("name example");
    expect(lines).toContain("bin example");
    expect(lines.some((l) => l.includes(`flag "-f --file" help="some input file"`))).toBe(true);
    expect(lines).toContain("flag --usage");
  });

  it("renders deeply nested command structure", () => {
    const root = new Command("myapp").version("1.0.0").description("My application");
    const db = new Command("db").description("Database operations");
    const migrate = new Command("migrate").description("Run migrations");
    const up = new Command("up").description("Apply migrations");
    const down = new Command("down").description("Rollback migrations");

    migrate.addCommand(up);
    migrate.addCommand(down);
    db.addCommand(migrate);
    root.addCommand(db);

    const output = generate(root);

    expect(output).toContain("cmd db");
    expect(output).toContain("help=\"Database operations\"");
    expect(output).toContain("cmd migrate");
    expect(output).toContain("help=\"Run migrations\"");
    expect(output).toContain("cmd up help=\"Apply migrations\"");
    expect(output).toContain("cmd down help=\"Rollback migrations\"");
  });
});

describe("JSON output", () => {
  it("generates JSON output with correct structure", () => {
    const cmd = new Command("mycli")
      .version("2.0.0")
      .description("A CLI tool")
      .option("--verbose", "Be verbose");
    const sub = new Command("run").description("Run something");
    cmd.addCommand(sub);

    const json = generateJSON(cmd);
    const parsed = JSON.parse(json);

    expect(parsed.name).toBe("mycli");
    expect(parsed.version).toBe("2.0.0");
    expect(parsed.about).toBe("A CLI tool");
    expect(parsed.flags).toHaveLength(1);
    expect(parsed.cmds).toHaveLength(1);
    expect(parsed.cmds[0].name).toBe("run");
  });

  it("includes choices in JSON output", () => {
    const cmd = new Command("deploy").addArgument(
      new Argument("<env>", "Environment").choices(["dev", "prod"])
    );

    const json = generateJSON(cmd);
    const parsed = JSON.parse(json);

    expect(parsed.args[0].choices).toEqual(["dev", "prod"]);
  });

  it("includes flag details in JSON", () => {
    const cmd = new Command("app")
      .requiredOption("--env <ENV>", "Target environment")
      .option("--no-color", "Disable color");

    const json = generateJSON(cmd);
    const parsed = JSON.parse(json);

    expect(parsed.flags).toHaveLength(2);
    const envFlag = parsed.flags.find((f: { name: string }) => f.name === "--env");
    expect(envFlag.required).toBe(true);
    expect(envFlag.arg.name).toBe("ENV");

    const colorFlag = parsed.flags.find((f: { name: string }) => f.name === "--no-color");
    expect(colorFlag.negate).toBe("--color");
  });

  it("handles custom bin name in JSON", () => {
    const cmd = new Command("app").description("A tool");
    const json = generateJSON(cmd, "my-tool");
    const parsed = JSON.parse(json);

    expect(parsed.bin).toBe("my-tool");
  });
});

describe("edge cases", () => {
  it("handles empty command with no options or args", () => {
    const cmd = new Command("empty");
    const output = generate(cmd);

    expect(output).toContain("name empty");
    expect(output).toContain("bin empty");
    expect(output).not.toContain("flag");
    expect(output).not.toContain("arg");
    expect(output).not.toContain("cmd");
  });

  it("handles command with only subcommands", () => {
    const root = new Command("app");
    root.addCommand(new Command("start").description("Start"));
    root.addCommand(new Command("stop").description("Stop"));

    const output = generate(root);

    expect(output).toContain("cmd start");
    expect(output).toContain("cmd stop");
  });

  it("handles option with makeOptionMandatory", () => {
    const cmd = new Command("app").addOption(
      new Option("--token <TOKEN>", "Auth token").makeOptionMandatory()
    );

    const output = generate(cmd);

    expect(output).toContain(`flag --token help="Auth token" required=#true`);
  });

  it("handles variadic option argument", () => {
    const cmd = new Command("app").option("--include <PATTERNS...>", "Include patterns");

    const spec = convertRoot(cmd);
    const includeFlag = spec.flags.find((f) => f.long === "include");

    expect(includeFlag?.var).toBe(true);
    expect(includeFlag?.arg?.var).toBe(true);
  });

  it("skips version field when not set", () => {
    const cmd = new Command("app").description("A tool");
    const output = generate(cmd);

    // Should not have a version line (only name, bin, about)
    expect(output).not.toContain("version ");
  });

  it("handles multiple flags on subcommand", () => {
    const root = new Command("app");
    const sub = new Command("build")
      .description("Build the project")
      .option("-o, --output <DIR>", "Output directory")
      .option("--minify", "Minify output")
      .option("--watch", "Watch for changes");
    root.addCommand(sub);

    const output = generate(root);

    expect(output).toContain(`flag "-o --output" help="Output directory"`);
    expect(output).toContain(`flag --minify help="Minify output"`);
    expect(output).toContain(`flag --watch help="Watch for changes"`);
  });
});
