package cobrausage

import (
	"encoding/json"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func newRootCmd(name string) *cobra.Command {
	cmd := &cobra.Command{Use: name}
	cmd.CompletionOptions.DisableDefaultCmd = true
	return cmd
}

func TestSimpleCommand_BasicCLI(t *testing.T) {
	root := newRootCmd("mycli")
	root.Version = "1.0.0"
	root.Short = "A CLI tool"
	root.Flags().BoolP("verbose", "v", false, "Enable verbose output")
	root.Flags().StringP("config", "c", "", "Config file path")

	output := GenerateKDL(root)

	assert.Contains(t, output, "name mycli")
	assert.Contains(t, output, "bin mycli")
	assert.Contains(t, output, `"1.0.0"`)
	assert.Contains(t, output, "verbose")
	assert.Contains(t, output, "config")
}

func TestSimpleCommand_GeneratedComment(t *testing.T) {
	root := newRootCmd("app")
	output := GenerateKDL(root)
	assert.Contains(t, output, "// @generated by cobra-usage from cobra metadata")
}

func TestSimpleCommand_CustomBin(t *testing.T) {
	root := newRootCmd("app")
	output := GenerateKDL(root, "my-app")
	assert.Contains(t, output, "bin my-app")
}

func TestVersion_ExtractsVersion(t *testing.T) {
	root := newRootCmd("app")
	root.Version = "2.0.0"
	spec := Convert(root)
	assert.Equal(t, "2.0.0", spec.Version)
}

func TestVersion_SkipsWhenNotSet(t *testing.T) {
	root := newRootCmd("app")
	output := GenerateKDL(root)
	assert.NotContains(t, output, "version ")
}

func TestAbout_ExtractsShort(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "A simple CLI tool"
	spec := Convert(root)
	assert.Equal(t, "A simple CLI tool", spec.About)
}

func TestAbout_ExtractsLongWhenNoShort(t *testing.T) {
	root := newRootCmd("app")
	root.Long = "A longer description"
	spec := Convert(root)
	assert.Equal(t, "A longer description", spec.About)
}

func TestAbout_SetsLongWhenBothPresent(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "Short"
	root.Long = "Long description"
	spec := Convert(root)
	assert.Equal(t, "Short", spec.About)
	assert.Equal(t, "Long description", spec.Long)
}

func TestNestedSubcommands_Recursive(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "An app"
	sub := &cobra.Command{Use: "db", Short: "Database ops"}
	nested := &cobra.Command{Use: "migrate", Short: "Run migrations"}
	sub.AddCommand(nested)
	root.AddCommand(sub)

	output := GenerateKDL(root)

	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, `"Database ops"`)
	assert.Contains(t, output, "cmd migrate")
	assert.Contains(t, output, `"Run migrations"`)
}

func TestNestedSubcommands_DeepNesting(t *testing.T) {
	root := newRootCmd("myapp")
	root.Version = "1.0.0"
	root.Short = "My application"
	db := &cobra.Command{Use: "db", Short: "Database operations"}
	migrate := &cobra.Command{Use: "migrate", Short: "Run migrations"}
	up := &cobra.Command{Use: "up", Short: "Apply migrations"}
	down := &cobra.Command{Use: "down", Short: "Rollback migrations"}
	migrate.AddCommand(up, down)
	db.AddCommand(migrate)
	root.AddCommand(db)

	output := GenerateKDL(root)

	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, `"Database operations"`)
	assert.Contains(t, output, "cmd migrate")
	assert.Contains(t, output, `"Run migrations"`)
	assert.Contains(t, output, "cmd up")
	assert.Contains(t, output, "cmd down")
}

func TestOptions_ShortAndLong(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().BoolP("verbose", "v", false, "Be verbose")

	output := GenerateKDL(root)
	assert.Contains(t, output, `flag "-v --verbose"`)
}

func TestOptions_RequiredFlag(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("env", "", "Target environment")
	root.Flags().SetAnnotation("env", requiredFlagAnnotation, []string{"true"})

	output := GenerateKDL(root)
	assert.Contains(t, output, "required=#true")
}

func TestOptions_DefaultString(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("format", "json", "Output format")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "format")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"json"}, flag.Default)
}

func TestOptions_DefaultNumberAsString(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("retries", "3", "Number of retries")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "retries")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"3"}, flag.Default)
}

func TestOptions_BoolDefaultTrue(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("color", true, "Enable color")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "color")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.DefaultBool)
	assert.True(t, *flag.DefaultBool)
}

func TestOptions_SkipsBoolDefaultFalse(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("force", false, "Force the operation")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.DefaultBool)
	assert.Nil(t, flag.Default)
}

func TestOptions_DefaultStringZero(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("port", "0", "Port number")

	output := GenerateKDL(root)
	assert.Contains(t, output, `default="0"`)
}

func TestOptions_Choices(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("format", "", "Output format")
	root.RegisterFlagCompletionFunc("format", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"json", "yaml", "toml"}, cobra.ShellCompDirectiveNoFileComp
	})

	spec := Convert(root)
	flag := findFlag(spec.Flags, "format")
	assert.NotNil(t, flag)
	// Cobra doesn't expose choices as part of flag definition; choices come from completion
	// We test that the flag is still converted correctly
	assert.Equal(t, "format", flag.Long)
}

func TestOptions_HiddenOption(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("secret", "", "Secret option")
	root.Flags().MarkHidden("secret")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "secret")
	assert.NotNil(t, flag)
	assert.True(t, flag.Hide)
}

func TestOptions_ArrayOption(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().StringArray("include", []string{}, "Include patterns")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "include")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
}

func TestOptions_StringSliceOption(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().StringSlice("tags", []string{}, "Tags")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "tags")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
}

func TestBooleanFlag_NoArg(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("force", false, "Force the operation")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.Arg)
}

func TestBooleanFlag_WithShort(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().BoolP("force", "f", false, "Force the operation")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Equal(t, "f", flag.Short)
	assert.Equal(t, "force", flag.Long)
}

func TestNegatedOptions_NoPrefix(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("no-color", false, "Disable color")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "no-color")
	assert.NotNil(t, flag)
	// Cobra doesn't have native negate support like Commander's --no-
	// The flag is just a regular boolean flag named "no-color"
	assert.Equal(t, "no-color", flag.Long)
}

func TestEnvVars_NotSet(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("token", "", "Auth token")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "token")
	assert.NotNil(t, flag)
	// Cobra/pflag doesn't have native env var support
	assert.Equal(t, "", flag.Env)
}

func TestDeprecatedOptions_Flag(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("old-flag", "", "Old flag")
	root.Flags().MarkDeprecated("old-flag", "Use --new-flag instead")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "old-flag")
	assert.NotNil(t, flag)
	assert.Equal(t, "Use --new-flag instead", flag.Deprecated)
}

func TestSkipsBuiltinFlags_Help(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("custom", "", "A custom flag")

	spec := Convert(root)
	flagNames := collectFlagNames(spec.Flags)
	assert.NotContains(t, flagNames, "help")
	assert.Contains(t, flagNames, "custom")
}

func TestPersistentFlags_MarkedGlobal(t *testing.T) {
	root := newRootCmd("app")
	root.PersistentFlags().Bool("debug", false, "Debug mode")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "debug")
	assert.NotNil(t, flag)
	assert.True(t, flag.Global)
}

func TestPersistentFlags_LocalNotGlobal(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("verbose", false, "Be verbose")
	root.PersistentFlags().Bool("debug", false, "Debug mode")

	spec := Convert(root)
	verbose := findFlag(spec.Flags, "verbose")
	debug := findFlag(spec.Flags, "debug")
	assert.NotNil(t, verbose)
	assert.False(t, verbose.Global)
	assert.NotNil(t, debug)
	assert.True(t, debug.Global)
}

func TestCommands_Subcommands(t *testing.T) {
	root := newRootCmd("app")
	root.AddCommand(&cobra.Command{Use: "add", Short: "Add a file"})
	root.AddCommand(&cobra.Command{Use: "remove", Short: "Remove files"})

	output := GenerateKDL(root)
	assert.Contains(t, output, "cmd add")
	assert.Contains(t, output, "cmd remove")
}

func TestCommands_Aliases(t *testing.T) {
	root := newRootCmd("app")
	install := &cobra.Command{Use: "install", Aliases: []string{"i", "add"}, Short: "Install packages"}
	root.AddCommand(install)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "install")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "i")
	assert.Contains(t, cmd.Aliases, "add")
}

func TestCommands_SingleAlias(t *testing.T) {
	root := newRootCmd("app")
	remove := &cobra.Command{Use: "remove", Aliases: []string{"rm"}, Short: "Remove packages"}
	root.AddCommand(remove)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "remove")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "rm")
}

func TestCommands_HiddenCommand(t *testing.T) {
	root := newRootCmd("app")
	secret := &cobra.Command{Use: "secret", Hidden: true}
	root.AddCommand(secret)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "secret")
	assert.NotNil(t, cmd)
	assert.True(t, cmd.Hide)
}

func TestCommands_NestedSubcommands(t *testing.T) {
	root := newRootCmd("app")
	db := &cobra.Command{Use: "db", Short: "Database ops"}
	db.AddCommand(&cobra.Command{Use: "migrate", Short: "Run migrations"})
	root.AddCommand(db)

	output := GenerateKDL(root)
	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, "cmd migrate")
}

func TestCommands_MultipleFlagsOnSubcommand(t *testing.T) {
	root := newRootCmd("app")
	build := &cobra.Command{Use: "build", Short: "Build the project"}
	build.Flags().StringP("output", "o", "", "Output directory")
	build.Flags().Bool("minify", false, "Minify output")
	build.Flags().Bool("watch", false, "Watch for changes")
	root.AddCommand(build)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "build")
	assert.NotNil(t, cmd)
	assert.Equal(t, 3, len(cmd.Flags))
	flagNames := collectFlagNames(cmd.Flags)
	assert.Contains(t, flagNames, "output")
	assert.Contains(t, flagNames, "minify")
	assert.Contains(t, flagNames, "watch")
}

func TestPositionalArgs_Required(t *testing.T) {
	root := newRootCmd("app")
	add := &cobra.Command{Use: "add <file>", Short: "Add a file"}
	root.AddCommand(add)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "file", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
}

func TestPositionalArgs_Optional(t *testing.T) {
	root := newRootCmd("app")
	list := &cobra.Command{Use: "list [filter]", Short: "List items"}
	root.AddCommand(list)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "list")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "filter", cmd.Args[0].Name)
	assert.False(t, cmd.Args[0].Required)
}

func TestPositionalArgs_Variadic(t *testing.T) {
	root := newRootCmd("app")
	add := &cobra.Command{Use: "add <files...>", Short: "Add files"}
	root.AddCommand(add)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "files", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Var)
}

func TestPositionalArgs_Mixed(t *testing.T) {
	root := newRootCmd("app")
	copy := &cobra.Command{Use: "copy <source> [dest]", Short: "Copy files"}
	root.AddCommand(copy)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "copy")
	assert.NotNil(t, cmd)
	assert.Equal(t, 2, len(cmd.Args))
	assert.Equal(t, "source", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
	assert.Equal(t, "dest", cmd.Args[1].Name)
	assert.False(t, cmd.Args[1].Required)
}

func TestSubcommandRequired_NoRunFunc(t *testing.T) {
	root := newRootCmd("app")
	db := &cobra.Command{Use: "db", Short: "Database ops"}
	db.AddCommand(&cobra.Command{Use: "migrate", Short: "Migrate", Run: func(cmd *cobra.Command, args []string) {}})
	root.AddCommand(db)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "db")
	assert.NotNil(t, cmd)
	assert.True(t, cmd.SubcommandRequired)
}

func TestSubcommandRequired_WithRunFunc(t *testing.T) {
	root := newRootCmd("app")
	db := &cobra.Command{Use: "db", Short: "Database ops", Run: func(cmd *cobra.Command, args []string) {}}
	db.AddCommand(&cobra.Command{Use: "migrate", Short: "Migrate", Run: func(cmd *cobra.Command, args []string) {}})
	root.AddCommand(db)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "db")
	assert.NotNil(t, cmd)
	assert.False(t, cmd.SubcommandRequired)
}

func TestLongHelp_BothShortAndLong(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "Short help"
	root.Long = "This is a much longer description of the app."

	output := GenerateKDL(root)
	assert.Contains(t, output, `"Short help"`)
	assert.Contains(t, output, `"This is a much longer description of the app."`)
}

func TestSpecialCharEscaping_Help(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("format", "", "Output format:\n  json\n  yaml")

	output := GenerateKDL(root)
	assert.Contains(t, output, "help=")
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_BasicCLI(t *testing.T) {
	root := newRootCmd("app")
	root.Version = "1.0.0"
	root.Flags().BoolP("verbose", "v", false, "Be verbose")
	root.Flags().StringP("file", "f", "", "Input file")

	output := GenerateKDL(root)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_WithCommands(t *testing.T) {
	root := newRootCmd("app")
	root.AddCommand(&cobra.Command{Use: "add <file>", Short: "Add a file"})
	root.AddCommand(&cobra.Command{Use: "remove", Short: "Remove files"})

	output := GenerateKDL(root)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_NestedCommands(t *testing.T) {
	root := newRootCmd("app")
	config := &cobra.Command{Use: "config", Short: "Config"}
	config.AddCommand(&cobra.Command{Use: "get", Short: "Get value", Run: func(cmd *cobra.Command, args []string) {}})
	root.AddCommand(config)

	output := GenerateKDL(root)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestGenerateKDL_IsAlias(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "A CLI"
	kdl := GenerateKDL(root)
	spec := Convert(root)
	assert.Equal(t, usagespec.Generate(spec, "kdl", "@generated by cobra-usage from cobra metadata"), kdl)
}

func TestJSONOutput_CorrectStructure(t *testing.T) {
	root := newRootCmd("mycli")
	root.Version = "2.0.0"
	root.Short = "A CLI tool"
	root.Flags().BoolP("verbose", "v", false, "Be verbose")
	run := &cobra.Command{Use: "run", Short: "Run something", Run: func(cmd *cobra.Command, args []string) {}}
	root.AddCommand(run)

	jsonStr := GenerateJSON(root)
	var parsed map[string]interface{}
	err := json.Unmarshal([]byte(jsonStr), &parsed)
	assert.NoError(t, err)
	assert.Equal(t, "mycli", parsed["name"])
	assert.Equal(t, "mycli", parsed["bin"])
	assert.Equal(t, "2.0.0", parsed["version"])
	assert.Equal(t, "A CLI tool", parsed["about"])
}

func TestJSONOutput_FlagDetails(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("env", "", "Target environment")
	root.Flags().SetAnnotation("env", requiredFlagAnnotation, []string{"true"})

	jsonStr := GenerateJSON(root)
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	flags := parsed["flags"].([]interface{})
	assert.Equal(t, 1, len(flags))
	flag := flags[0].(map[string]interface{})
	assert.Equal(t, true, flag["required"])
}

func TestJSONOutput_CustomBin(t *testing.T) {
	root := newRootCmd("app")
	root.Short = "A tool"
	jsonStr := GenerateJSON(root, "my-tool")
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	assert.Equal(t, "my-tool", parsed["bin"])
}

func TestConvertRoot_CorrectStructure(t *testing.T) {
	root := newRootCmd("mycli")
	root.Version = "2.0.0"
	root.Short = "A CLI tool"
	root.Flags().BoolP("verbose", "v", false, "Be verbose")

	spec := ConvertRoot(root)

	assert.Equal(t, "mycli", spec.Name)
	assert.Equal(t, "mycli", spec.Bin)
	assert.Equal(t, "2.0.0", spec.Version)
	assert.Equal(t, "A CLI tool", spec.About)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "verbose", spec.Flags[0].Long)
	assert.Equal(t, "v", spec.Flags[0].Short)
}

func TestConvertRoot_ArgsFromCommand(t *testing.T) {
	root := newRootCmd("cmd")
	add := &cobra.Command{Use: "add <file>", Short: "Add a file"}
	root.AddCommand(add)

	spec := ConvertRoot(root)
	cmd := findCmd(spec.Cmds, "add")
	assert.NotNil(t, cmd)
	assert.Equal(t, 1, len(cmd.Args))
	assert.Equal(t, "file", cmd.Args[0].Name)
	assert.True(t, cmd.Args[0].Required)
}

func TestEdgeCases_EmptyCLI(t *testing.T) {
	root := newRootCmd("empty")
	output := GenerateKDL(root)

	assert.Contains(t, output, "name empty")
	assert.Contains(t, output, "bin empty")
	assert.NotContains(t, output, "flag")
	assert.NotContains(t, output, "arg ")
	assert.NotContains(t, output, "cmd ")
}

func TestEdgeCases_OnlySubcommands(t *testing.T) {
	root := newRootCmd("app")
	root.AddCommand(&cobra.Command{Use: "start", Short: "Start", Run: func(cmd *cobra.Command, args []string) {}})
	root.AddCommand(&cobra.Command{Use: "stop", Short: "Stop", Run: func(cmd *cobra.Command, args []string) {}})

	output := GenerateKDL(root)
	assert.Contains(t, output, "cmd start")
	assert.Contains(t, output, "cmd stop")
}

func TestEdgeCases_FlagWithOnlyShort(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().BoolP("v", "v", false, "Be verbose")

	spec := Convert(root)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "v", spec.Flags[0].Short)
}

func TestEdgeCases_FlagWithOnlyLong(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Bool("verbose", false, "Be verbose")

	spec := Convert(root)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "verbose", spec.Flags[0].Long)
	assert.Equal(t, "", spec.Flags[0].Short)
}

func TestFullOutput_CompleteExample(t *testing.T) {
	root := newRootCmd("example")
	root.Version = "1.0.0"
	root.Short = "An example CLI"
	root.Flags().StringP("file", "f", "", "Some input file")
	root.Flags().Bool("verbose", false, "Enable verbose output")

	output := GenerateKDL(root, "example")

	assert.Contains(t, output, "name example")
	assert.Contains(t, output, "bin example")
	assert.Contains(t, output, `"1.0.0"`)
	assert.Contains(t, output, `"An example CLI"`)
	assert.Contains(t, output, "file")
	assert.Contains(t, output, "verbose")
}

func TestDeprecatedCommand(t *testing.T) {
	root := newRootCmd("app")
	old := &cobra.Command{Use: "old-cmd", Deprecated: "Use new-cmd instead"}
	root.AddCommand(old)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "old-cmd")
	assert.NotNil(t, cmd)
	assert.Equal(t, "Use new-cmd instead", cmd.Deprecated)
}

func TestCommandWithPersistentFlagsOnSubcommand(t *testing.T) {
	root := newRootCmd("app")
	db := &cobra.Command{Use: "db", Short: "Database ops"}
	db.PersistentFlags().Bool("dry-run", false, "Dry run mode")
	db.AddCommand(&cobra.Command{Use: "migrate", Short: "Migrate", Run: func(cmd *cobra.Command, args []string) {}})
	root.AddCommand(db)

	spec := Convert(root)
	cmd := findCmd(spec.Cmds, "db")
	assert.NotNil(t, cmd)
	dryRun := findFlag(cmd.Flags, "dry-run")
	assert.NotNil(t, dryRun)
	assert.True(t, dryRun.Global)
}

func TestPersistentFlagNotDuplicated(t *testing.T) {
	root := newRootCmd("app")
	root.PersistentFlags().Bool("verbose", false, "Be verbose")
	sub := &cobra.Command{Use: "sub", Short: "Sub", Run: func(cmd *cobra.Command, args []string) {}}
	root.AddCommand(sub)

	spec := Convert(root)
	assert.Equal(t, 1, len(spec.Flags))

	subSpec := findCmd(spec.Cmds, "sub")
	assert.NotNil(t, subSpec)
	// Persistent flags are inherited by subcommands, but we only include them on root
	// and subcommands that have them as local flags should not duplicate
}

func TestIntFlag_Default(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().Int("port", 8080, "Port number")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "port")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"8080"}, flag.Default)
	assert.NotNil(t, flag.Arg)
}

func TestSkipHelpCommand(t *testing.T) {
	root := newRootCmd("app")
	root.AddCommand(&cobra.Command{Use: "start", Short: "Start", Run: func(cmd *cobra.Command, args []string) {}})

	spec := Convert(root)
	// Cobra adds a "help" subcommand by default; we should not include it
	cmdNames := collectCmdNames(spec.Cmds)
	assert.NotContains(t, cmdNames, "help")
	assert.Contains(t, cmdNames, "start")
}

func TestCompletionCommand_Skipped(t *testing.T) {
	root := newRootCmd("app")
	root.CompletionOptions.DisableDefaultCmd = true
	root.AddCommand(&cobra.Command{Use: "start", Short: "Start", Run: func(cmd *cobra.Command, args []string) {}})

	spec := Convert(root)
	cmdNames := collectCmdNames(spec.Cmds)
	assert.NotContains(t, cmdNames, "completion")
}

func TestRootPositionalArgs(t *testing.T) {
	root := &cobra.Command{Use: "myapp <input>"}

	spec := Convert(root)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, "input", spec.Args[0].Name)
	assert.True(t, spec.Args[0].Required)
}

func TestFlagArgName_Uppercase(t *testing.T) {
	root := newRootCmd("app")
	root.Flags().String("output-dir", "", "Output directory")

	spec := Convert(root)
	flag := findFlag(spec.Flags, "output-dir")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.Arg)
	assert.Equal(t, "OUTPUT_DIR", flag.Arg.Name)
}

func findFlag(flags []usagespec.SpecFlag, name string) *usagespec.SpecFlag {
	for i := range flags {
		if flags[i].Long == name {
			return &flags[i]
		}
	}
	return nil
}

func findCmd(cmds []usagespec.SpecCommand, name string) *usagespec.SpecCommand {
	for i := range cmds {
		if cmds[i].Name == name {
			return &cmds[i]
		}
	}
	return nil
}

func collectFlagNames(flags []usagespec.SpecFlag) []string {
	names := make([]string, len(flags))
	for i, f := range flags {
		names[i] = f.Long
	}
	return names
}

func collectCmdNames(cmds []usagespec.SpecCommand) []string {
	names := make([]string, len(cmds))
	for i, c := range cmds {
		names[i] = c.Name
	}
	return names
}
