package cobrausage

import (
	"github.com/spf13/cobra"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func Generate(cmd *cobra.Command, format string, comment string) string {
	spec := Convert(cmd)
	return usagespec.Generate(spec, format, comment)
}

func GenerateKDL(cmd *cobra.Command, bin ...string) string {
	spec := Convert(cmd)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "kdl", "@generated by cobra-usage from cobra metadata")
}

func GenerateJSON(cmd *cobra.Command, bin ...string) string {
	spec := Convert(cmd)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "json", "")
}

func ConvertRoot(cmd *cobra.Command) usagespec.Spec {
	return Convert(cmd)
}
