package kongusage

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/alecthomas/kong"
	"github.com/stretchr/testify/assert"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func mustKong(cli interface{}, opts ...kong.Option) *kong.Kong {
	k, err := kong.New(cli, opts...)
	if err != nil {
		panic(err)
	}
	return k
}

type simpleCLI struct {
	Verbose bool   `short:"v" help:"Enable verbose output"`
	Config  string `short:"c" help:"Config file path"`
}

func TestSimpleCommand_BasicCLI(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("mycli"))
	k.Model.Help = "A CLI tool"
	output := GenerateKDL(k)

	assert.Contains(t, output, "name mycli")
	assert.Contains(t, output, "bin mycli")
	assert.Contains(t, output, "verbose")
	assert.Contains(t, output, "config")
}

func TestSimpleCommand_GeneratedComment(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, "// @generated by kong-usage from kong metadata")
}

func TestSimpleCommand_CustomBin(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	output := GenerateKDL(k, "my-app")
	assert.Contains(t, output, "bin my-app")
}

func TestVersion_NotSet(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, "", spec.Version)
}

func TestAbout_ExtractsHelp(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	k.Model.Help = "A simple CLI tool"
	spec := Convert(k)
	assert.Equal(t, "A simple CLI tool", spec.About)
}

func TestAbout_SetsLongWhenDetail(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	k.Model.Help = "Short"
	k.Model.Detail = "Detailed description"
	spec := Convert(k)
	assert.Equal(t, "Short", spec.About)
	assert.Equal(t, "Detailed description", spec.Long)
}

type dbCLI struct {
	Db struct {
		Migrate struct {
			Up   struct{} `cmd help:"Apply migrations"`
			Down struct{} `cmd help:"Rollback migrations"`
		} `cmd help:"Run migrations"`
	} `cmd help:"Database ops"`
}

func TestNestedSubcommands_Recursive(t *testing.T) {
	k := mustKong(&dbCLI{}, kong.Name("app"))
	output := GenerateKDL(k)

	assert.Contains(t, output, "cmd db")
	assert.Contains(t, output, `"Database ops"`)
	assert.Contains(t, output, "cmd migrate")
	assert.Contains(t, output, `"Run migrations"`)
}

func TestNestedSubcommands_DeepNesting(t *testing.T) {
	k := mustKong(&dbCLI{}, kong.Name("app"))
	output := GenerateKDL(k)

	assert.Contains(t, output, "cmd up")
	assert.Contains(t, output, `"Apply migrations"`)
	assert.Contains(t, output, "cmd down")
	assert.Contains(t, output, `"Rollback migrations"`)
}

type optionsCLI struct {
	Verbose bool   `short:"v" help:"Be verbose"`
	Format  string `help:"Output format" enum:"json,yaml,toml" default:"json"`
	Env     string `help:"Target environment" required:""`
	Output  string `help:"Output directory" default:"./dist"`
}

func TestOptions_ShortAndLong(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, `flag "-v --verbose"`)
}

func TestOptions_RequiredFlag(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, "required=#true")
}

func TestOptions_DefaultString(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "output")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"./dist"}, flag.Default)
}

func TestOptions_BoolDefaultTrue(t *testing.T) {
	cli := struct {
		Color bool `help:"Enable color" default:"true"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "color")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.DefaultBool)
	assert.True(t, *flag.DefaultBool)
}

func TestOptions_SkipsBoolDefaultFalse(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "verbose")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.DefaultBool)
	assert.Nil(t, flag.Default)
}

func TestOptions_Choices(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "format")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.Arg)
	assert.NotNil(t, flag.Arg.Choices)
	assert.Equal(t, []string{"json", "yaml", "toml"}, flag.Arg.Choices.Values)
}

type hiddenCLI struct {
	Secret string `help:"Secret option" hidden:""`
}

func TestOptions_HiddenOption(t *testing.T) {
	k := mustKong(&hiddenCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "secret")
	assert.NotNil(t, flag)
	assert.True(t, flag.Hide)
}

type sliceCLI struct {
	Include []string `help:"Include patterns"`
}

func TestOptions_ArrayOption(t *testing.T) {
	k := mustKong(&sliceCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "include")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
	assert.NotNil(t, flag.Arg)
	assert.True(t, flag.Arg.Var)
}

type boolCLI struct {
	Force bool `help:"Force the operation"`
}

func TestBooleanFlag_NoArg(t *testing.T) {
	k := mustKong(&boolCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Nil(t, flag.Arg)
}

func TestBooleanFlag_WithShort(t *testing.T) {
	cli := struct {
		Force bool `short:"f" help:"Force the operation"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "force")
	assert.NotNil(t, flag)
	assert.Equal(t, "f", flag.Short)
	assert.Equal(t, "force", flag.Long)
}

type negateCLI struct {
	Color bool `help:"Enable color" negatable:""`
}

func TestNegatedOptions_Negatable(t *testing.T) {
	k := mustKong(&negateCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "color")
	assert.NotNil(t, flag)
	assert.Equal(t, "--no-color", flag.Negate)
}

type envCLI struct {
	Token string `help:"Auth token" env:"MYCLI_TOKEN"`
}

func TestEnvVars_EnvSet(t *testing.T) {
	k := mustKong(&envCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "token")
	assert.NotNil(t, flag)
	assert.Equal(t, "MYCLI_TOKEN", flag.Env)
}

func TestEnvVars_NotSet(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	spec := Convert(k)
	for _, f := range spec.Flags {
		assert.Equal(t, "", f.Env)
	}
}

type counterCLI struct {
	Verbose int `type:"counter" short:"v" help:"Verbosity level"`
}

func TestCounterOption(t *testing.T) {
	k := mustKong(&counterCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "verbose")
	assert.NotNil(t, flag)
	assert.True(t, flag.Count)
}

type aliasCLI struct {
	Install struct{} `cmd help:"Install packages" aliases:"i,add"`
}

func TestCommands_Aliases(t *testing.T) {
	k := mustKong(&aliasCLI{}, kong.Name("app"))
	spec := Convert(k)
	cmd := findCmd(spec.Cmds, "install")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "i")
	assert.Contains(t, cmd.Aliases, "add")
}

type singleAliasCLI struct {
	Remove struct{} `cmd help:"Remove packages" aliases:"rm"`
}

func TestCommands_SingleAlias(t *testing.T) {
	k := mustKong(&singleAliasCLI{}, kong.Name("app"))
	spec := Convert(k)
	cmd := findCmd(spec.Cmds, "remove")
	assert.NotNil(t, cmd)
	assert.Contains(t, cmd.Aliases, "rm")
}

type hiddenCmdCLI struct {
	Secret struct{} `cmd help:"Secret" hidden:""`
	Open   struct{} `cmd help:"Open"`
}

func TestCommands_HiddenCommand(t *testing.T) {
	k := mustKong(&hiddenCmdCLI{}, kong.Name("app"))
	spec := Convert(k)
	cmd := findCmd(spec.Cmds, "secret")
	assert.NotNil(t, cmd)
	assert.True(t, cmd.Hide)
}

type subcmdFlagsCLI struct {
	Build struct {
		Output string `short:"o" help:"Output directory"`
		Minify bool   `help:"Minify output"`
		Watch  bool   `help:"Watch for changes"`
	} `cmd help:"Build the project"`
}

func TestCommands_MultipleFlagsOnSubcommand(t *testing.T) {
	k := mustKong(&subcmdFlagsCLI{}, kong.Name("app"))
	spec := Convert(k)
	cmd := findCmd(spec.Cmds, "build")
	assert.NotNil(t, cmd)
	assert.Equal(t, 3, len(cmd.Flags))
	flagNames := collectFlagNames(cmd.Flags)
	assert.Contains(t, flagNames, "output")
	assert.Contains(t, flagNames, "minify")
	assert.Contains(t, flagNames, "watch")
}

type positionalCLI struct {
	File string `arg help:"Input file" required:""`
}

func TestPositionalArgs_Required(t *testing.T) {
	k := mustKong(&positionalCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, "file", spec.Args[0].Name)
	assert.True(t, spec.Args[0].Required)
}

type optionalPosCLI struct {
	Filter string `arg optional help:"Filter"`
}

func TestPositionalArgs_Optional(t *testing.T) {
	k := mustKong(&optionalPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, "filter", spec.Args[0].Name)
	assert.False(t, spec.Args[0].Required)
}

type variadicPosCLI struct {
	Files []string `arg help:"Input files"`
}

func TestPositionalArgs_Variadic(t *testing.T) {
	k := mustKong(&variadicPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, "files", spec.Args[0].Name)
	assert.True(t, spec.Args[0].Var)
}

type mixedPosCLI struct {
	Source string `arg required help:"Source"`
	Dest   string `arg optional help:"Destination"`
}

func TestPositionalArgs_Mixed(t *testing.T) {
	k := mustKong(&mixedPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 2, len(spec.Args))
	assert.Equal(t, "source", spec.Args[0].Name)
	assert.True(t, spec.Args[0].Required)
	assert.Equal(t, "dest", spec.Args[1].Name)
	assert.False(t, spec.Args[1].Required)
}

type enumPosCLI struct {
	Format string `arg help:"Format" enum:"json,yaml" required:""`
}

func TestPositionalArgs_Choices(t *testing.T) {
	k := mustKong(&enumPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.NotNil(t, spec.Args[0].Choices)
	assert.Equal(t, []string{"json", "yaml"}, spec.Args[0].Choices.Values)
}

func TestSkipsBuiltinFlags_Help(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	spec := Convert(k)
	flagNames := collectFlagNames(spec.Flags)
	assert.NotContains(t, flagNames, "help")
}

type specialCharCLI struct {
	Format string `help:"Output format:\n  json\n  yaml"`
}

func TestSpecialCharEscaping_Help(t *testing.T) {
	k := mustKong(&specialCharCLI{}, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, "help=")
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_BasicCLI(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	output := GenerateKDL(k)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_WithCommands(t *testing.T) {
	cli := struct {
		Add    struct{} `cmd help:"Add a file"`
		Remove struct{} `cmd help:"Remove files"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	output := GenerateKDL(k)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestKDLRoundtrip_NestedCommands(t *testing.T) {
	cli := struct {
		Config struct {
			Get struct{} `cmd help:"Get value"`
		} `cmd help:"Config"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	output := GenerateKDL(k)
	assert.NotPanics(t, func() { usagespec.ValidateKDL(output) })
}

func TestGenerateKDL_IsAlias(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	k.Model.Help = "A CLI"
	kdl := GenerateKDL(k)
	spec := Convert(k)
	assert.Equal(t, usagespec.Generate(spec, "kdl", "@generated by kong-usage from kong metadata"), kdl)
}

func TestJSONOutput_CorrectStructure(t *testing.T) {
	cli := struct {
		Run struct{} `cmd help:"Run something"`
	}{}
	k := mustKong(&cli, kong.Name("mycli"))
	k.Model.Help = "A CLI tool"

	jsonStr := GenerateJSON(k)
	var parsed map[string]interface{}
	err := json.Unmarshal([]byte(jsonStr), &parsed)
	assert.NoError(t, err)
	assert.Equal(t, "mycli", parsed["name"])
	assert.Equal(t, "A CLI tool", parsed["about"])
}

func TestJSONOutput_FlagDetails(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("app"))
	jsonStr := GenerateJSON(k)
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	flags := parsed["flags"].([]interface{})
	found := false
	for _, f := range flags {
		flag := f.(map[string]interface{})
		if name, ok := flag["name"].(string); ok && strings.Contains(name, "env") {
			if flag["required"] == true {
				found = true
			}
		}
	}
	assert.True(t, found)
}

func TestJSONOutput_CustomBin(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("app"))
	k.Model.Help = "A tool"
	jsonStr := GenerateJSON(k, "my-tool")
	var parsed map[string]interface{}
	json.Unmarshal([]byte(jsonStr), &parsed)
	assert.Equal(t, "my-tool", parsed["bin"])
}

func TestConvertRoot_CorrectStructure(t *testing.T) {
	k := mustKong(&simpleCLI{}, kong.Name("mycli"))
	k.Model.Help = "A CLI tool"

	spec := ConvertRoot(k)

	assert.Equal(t, "mycli", spec.Name)
	assert.Equal(t, "mycli", spec.Bin)
	assert.Equal(t, "A CLI tool", spec.About)
	assert.Equal(t, 2, len(spec.Flags))
}

func TestEdgeCases_EmptyCLI(t *testing.T) {
	cli := struct{}{}
	k := mustKong(&cli, kong.Name("empty"))
	output := GenerateKDL(k)

	assert.Contains(t, output, "name empty")
	assert.Contains(t, output, "bin empty")
}

func TestEdgeCases_OnlySubcommands(t *testing.T) {
	cli := struct {
		Start struct{} `cmd help:"Start"`
		Stop  struct{} `cmd help:"Stop"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, "cmd start")
	assert.Contains(t, output, "cmd stop")
}

func TestEdgeCases_FlagWithOnlyLong(t *testing.T) {
	cli := struct {
		Verbose bool `help:"Be verbose"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Flags))
	assert.Equal(t, "verbose", spec.Flags[0].Long)
	assert.Equal(t, "", spec.Flags[0].Short)
}

func TestFullOutput_CompleteExample(t *testing.T) {
	k := mustKong(&optionsCLI{}, kong.Name("example"))
	k.Model.Help = "An example CLI"
	output := GenerateKDL(k, "example")

	assert.Contains(t, output, "name example")
	assert.Contains(t, output, "bin example")
	assert.Contains(t, output, `"An example CLI"`)
}

type defaultPosCLI struct {
	Name string `arg default:"world" help:"Name"`
}

func TestPositionalArgs_Default(t *testing.T) {
	k := mustKong(&defaultPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.Equal(t, []string{"world"}, spec.Args[0].Default)
}

type hiddenPosCLI struct {
	File string `arg help:"Input" hidden:""`
}

func TestPositionalArgs_Hidden(t *testing.T) {
	k := mustKong(&hiddenPosCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.True(t, spec.Args[0].Hide)
}

type xorCLI struct {
	Json  bool `help:"JSON output" xor:"format"`
	Yaml  bool `help:"YAML output" xor:"format"`
	Plain bool `help:"Plain output"`
}

func TestXorFlags(t *testing.T) {
	k := mustKong(&xorCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 3, len(spec.Flags))
}

func TestFlagArgName_Uppercase(t *testing.T) {
	cli := struct {
		OutputDir string `help:"Output directory"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "output-dir")
	assert.NotNil(t, flag)
	assert.NotNil(t, flag.Arg)
	assert.Equal(t, "OUTPUT_DIR", flag.Arg.Name)
}

type intFlagCLI struct {
	Port int `help:"Port number" default:"8080"`
}

func TestIntFlag_Default(t *testing.T) {
	k := mustKong(&intFlagCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "port")
	assert.NotNil(t, flag)
	assert.Equal(t, []string{"8080"}, flag.Default)
}

type mapFlagCLI struct {
	Tags map[string]string `help:"Tags"`
}

func TestMapFlag_IsVar(t *testing.T) {
	k := mustKong(&mapFlagCLI{}, kong.Name("app"))
	spec := Convert(k)
	flag := findFlag(spec.Flags, "tags")
	assert.NotNil(t, flag)
	assert.True(t, flag.Var)
}

func TestDefaultStringZero(t *testing.T) {
	cli := struct {
		Port string `help:"Port number" default:"0"`
	}{}
	k := mustKong(&cli, kong.Name("app"))
	output := GenerateKDL(k)
	assert.Contains(t, output, `default="0"`)
}

type nestedCmdFlagsCLI struct {
	Db struct {
		Migrate struct {
			Direction string `help:"Migration direction" enum:"up,down" default:"up"`
		} `cmd help:"Run migrations"`
	} `cmd help:"Database ops"`
}

func TestNestedCommandWithFlags(t *testing.T) {
	k := mustKong(&nestedCmdFlagsCLI{}, kong.Name("app"))
	spec := Convert(k)
	db := findCmd(spec.Cmds, "db")
	assert.NotNil(t, db)
	migrate := findCmd(db.Cmds, "migrate")
	assert.NotNil(t, migrate)
	assert.Equal(t, 1, len(migrate.Flags))
	assert.Equal(t, "direction", migrate.Flags[0].Long)
}

type posWithChoicesCLI struct {
	Format string `arg help:"Output format" enum:"json,yaml,toml" required:""`
}

func TestPositionalArgs_ChoicesMultiple(t *testing.T) {
	k := mustKong(&posWithChoicesCLI{}, kong.Name("app"))
	spec := Convert(k)
	assert.Equal(t, 1, len(spec.Args))
	assert.NotNil(t, spec.Args[0].Choices)
	assert.Equal(t, []string{"json", "yaml", "toml"}, spec.Args[0].Choices.Values)
}

func findFlag(flags []usagespec.SpecFlag, name string) *usagespec.SpecFlag {
	for i := range flags {
		if flags[i].Long == name {
			return &flags[i]
		}
	}
	return nil
}

func findCmd(cmds []usagespec.SpecCommand, name string) *usagespec.SpecCommand {
	for i := range cmds {
		if cmds[i].Name == name {
			return &cmds[i]
		}
	}
	return nil
}

func collectFlagNames(flags []usagespec.SpecFlag) []string {
	names := make([]string, len(flags))
	for i, f := range flags {
		names[i] = f.Long
	}
	return names
}
