package kongusage

import (
	"github.com/alecthomas/kong"
	usagespec "github.com/gaojunran/usage-integrations/packages/usage-spec-go"
)

func Generate(k *kong.Kong, format string, comment string) string {
	spec := Convert(k)
	return usagespec.Generate(spec, format, comment)
}

func GenerateKDL(k *kong.Kong, bin ...string) string {
	spec := Convert(k)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "kdl", "@generated by kong-usage from kong metadata")
}

func GenerateJSON(k *kong.Kong, bin ...string) string {
	spec := Convert(k)
	if len(bin) > 0 {
		spec.Bin = bin[0]
	}
	return usagespec.Generate(spec, "json", "")
}

func ConvertRoot(k *kong.Kong) usagespec.Spec {
	return Convert(k)
}
