import type { Argv } from "yargs";
import { convertRoot } from "./convert.js";
import { renderKDL, renderJSON, generate as coreGenerate } from "@usage-spec/core";
import type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices } from "@usage-spec/core";

export { convertRoot } from "./convert.js";
export { renderKDL } from "@usage-spec/core";
export type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices };

/**
 * Generates a usage spec in KDL format from a yargs instance.
 */
export function generate(y: Argv, binName?: string): string {
  const spec = convertRoot(y, binName);
  return coreGenerate(spec, {
    format: "kdl",
    comment: "@generated by @usage-spec/yargs from yargs metadata",
  });
}

/**
 * Generates a usage spec in KDL format from a yargs instance.
 */
export function generateKDL(y: Argv, binName?: string): string {
  return generate(y, binName);
}

/**
 * Generates a usage spec in JSON format from a yargs instance.
 */
export function generateJSON(y: Argv, binName?: string): string {
  const spec = convertRoot(y, binName);
  return coreGenerate(spec, { format: "json" });
}
