package jcommander_usage

import com.beust.jcommander.JCommander
import usage_spec.generate

fun generate(jc: JCommander, binName: String? = null): String {
    val spec = convertRoot(jc, binName)
    return generate(spec, format = "kdl", comment = "@generated by jcommander-usage from JCommander metadata")
}

fun generateKDL(jc: JCommander, binName: String? = null): String {
    return generate(jc, binName)
}

fun generateJSON(jc: JCommander, binName: String? = null): String {
    val spec = convertRoot(jc, binName)
    return generate(spec, format = "json")
}
