package jcommander_usage

import com.beust.jcommander.JCommander
import com.beust.jcommander.Parameter
import com.beust.jcommander.Parameters
import io.kotest.assertions.throwables.shouldNotThrowAny
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.booleans.shouldBeFalse
import io.kotest.matchers.booleans.shouldBeTrue
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import usage_spec.validateKDL

enum class TestFormat { JSON, YAML, TOML }
enum class TestEnv { DEV, STAGING, PROD }

class JCommanderUsageTest : FunSpec({

    context("simple command") {
        test("generates spec for a basic CLI with options") {
            @Parameters(commandNames = ["mycli"], commandDescription = "A simple CLI")
            class MyCli {
                @Parameter(names = ["-v", "--verbose"], description = "Enable verbose output")
                var verbose = false

                @Parameter(names = ["-c", "--config"], description = "Config file path")
                var config: String? = null
            }

            val jc = JCommander(MyCli())
            val output = generate(jc)

            output shouldContain "name mycli"
            output shouldContain "bin mycli"
            output shouldContain """flag "-v --verbose" help="Enable verbose output""""
            output shouldContain """flag "-c --config" help="Config file path""""
        }

        test("includes generated comment header") {
            class App
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain "// @generated by jcommander-usage from JCommander metadata"
        }

        test("uses custom bin name when provided") {
            class App
            val jc = JCommander(App())
            val output = generate(jc, "my-app")
            output shouldContain "bin my-app"
        }

        test("renders short-only flags") {
            class App {
                @Parameter(names = ["-v"], description = "Be verbose")
                var verbose = false
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """flag -v help="Be verbose""""
        }

        test("renders long-only flags") {
            class App {
                @Parameter(names = ["--verbose"], description = "Be verbose")
                var verbose = false
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """flag --verbose help="Be verbose""""
        }
    }

    context("global/persistent flags") {
        test("does not mark root-level flags as global") {
            class Run

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App {
                @Parameter(names = ["-d", "--debug"], description = "Enable debug mode")
                var debug = false
            }

            val jc = JCommander(App())
            jc.addCommand("run", Run())

            val output = generate(jc)

            output shouldContain """flag "-d --debug" help="Enable debug mode""""
            output shouldNotContain "global"
        }
    }

    context("nested subcommands") {
        test("renders subcommands recursively") {
            @Parameters(commandNames = ["nested"], commandDescription = "A nested subcommand")
            class Nested

            @Parameters(commandNames = ["sub"], commandDescription = "A subcommand")
            class Sub

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("sub", Sub())
            val subJc = jc.commands["sub"]!!
            subJc.addCommand("nested", Nested())

            val output = generate(jc)
            output shouldContain "cmd sub"
            output shouldContain "cmd nested"
        }
    }

    context("required options") {
        test("marks mandatory options as required") {
            class Deploy {
                @Parameter(names = ["--env"], description = "Target environment", required = true)
                var env: String? = null
            }
            val jc = JCommander(Deploy())
            val output = generate(jc)
            output shouldContain """flag --env help="Target environment" required=#true"""
        }
    }

    context("hidden") {
        test("hides commands and options") {
            @Parameters(commandNames = ["internal"], commandDescription = "Internal command", hidden = true)
            class HiddenCmd

            class App {
                @Parameter(names = ["--secret"], description = "Secret flag", hidden = true)
                var secret: String? = null
            }
            val jc = JCommander(App())
            jc.addCommand("internal", HiddenCmd())
            val output = generate(jc)
            output shouldContain "cmd internal hide=#true"
            output shouldContain """flag --secret help="Secret flag" hide=#true"""
        }
    }

    context("argument inference") {
        test("converts main parameter") {
            class Cmd {
                @Parameter(description = "Input file")
                var file: String? = null
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain """arg "[FILE]""""
        }

        test("converts required main parameter") {
            class Cmd {
                @Parameter(description = "Input file", required = true)
                var file: String? = null
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain "arg <FILE>"
        }

        test("converts variadic main parameter") {
            class Cmd {
                @Parameter(description = "Multiple files", variableArity = true)
                var files: List<String> = mutableListOf()
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain """arg "[FILES]…""""
            output shouldContain "var=#true"
        }

        test("converts flag with arity 0 as boolean") {
            class App {
                @Parameter(names = ["-c", "--cheese"], description = "Add cheese", arity = 0)
                var cheese = false
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """flag "-c --cheese""""
        }

        test("converts mixed required and optional main parameters") {
            class Cmd {
                @Parameter(description = "Source path", required = true)
                var source: String? = null
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain "arg <SOURCE>"
        }
    }

    context("choices") {
        test("renders choices for option arguments") {
            class Deploy {
                @Parameter(names = ["--format"], description = "Output format")
                var format: TestFormat? = null
            }
            val jc = JCommander(Deploy())
            val output = generate(jc)
            output shouldContain "choices"
            output shouldContain "JSON"
            output shouldContain "YAML"
            output shouldContain "TOML"
        }

        test("renders choices for positional arguments") {
            class Deploy {
                @Parameter(description = "Environment", required = true)
                var env: String? = null
            }
            val jc = JCommander(Deploy())
            val output = generate(jc)
            output shouldContain "arg <ENV>"
        }
    }

    context("default values") {
        test("renders default value for option") {
            class App {
                @Parameter(names = ["--output"], description = "Output format")
                var output = "json"

                @Parameter(names = ["--retries"], description = "Number of retries")
                var retries = 3
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """flag --output help="Output format" default=json"""
            output shouldContain """flag --retries help="Number of retries" default="3""""
        }

        test("renders default value for argument") {
            class Cmd {
                @Parameter(description = "Input file")
                var file = "default.txt"
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain "default=default.txt"
        }

        test("skips false default for boolean flags") {
            class App {
                @Parameter(names = ["--force"], description = "Force the operation")
                var force = false
            }
            val jc = JCommander(App())
            val output = generate(jc)
            val forceLine = output.split("\n").find { it.contains("flag --force") }
            forceLine shouldNotBe null
            forceLine shouldNotContain "default"
        }

        test("preserves true default for boolean flags") {
            class App {
                @Parameter(names = ["--color"], description = "Enable color")
                var color = true
            }
            val jc = JCommander(App())
            val output = generate(jc)
            val colorLine = output.split("\n").find { it.contains("flag --color") }
            colorLine shouldNotBe null
            colorLine shouldContain "default=#true"
        }

        test("preserves string zero as default") {
            class App {
                @Parameter(names = ["--port"], description = "Port number")
                var port = "0"
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """default="0""""
        }
    }

    context("boolean flags") {
        test("does not render arg for boolean flags") {
            class App {
                @Parameter(names = ["--force"], description = "Force the operation")
                var force = false
            }
            val jc = JCommander(App())
            val output = generate(jc)
            val forceLine = output.split("\n").find { it.contains("flag --force") }
            forceLine shouldNotBe null
            forceLine shouldNotContain "arg"
        }
    }

    context("skips builtin") {
        test("does not render --help flag") {
            class App {
                @Parameter(names = ["--custom"], description = "A custom flag")
                var custom: String? = null
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldNotContain "flag --help"
            output shouldContain "flag --custom"
        }

        test("does not render --version flag") {
            class App {
                @Parameter(names = ["--version"], description = "Show version", help = true)
                var version = false

                @Parameter(names = ["--custom"], description = "A custom flag")
                var custom: String? = null
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldNotContain "flag --version"
            output shouldContain "flag --custom"
        }
    }

    context("subcommand_required") {
        test("sets subcommand_required for commands with subcommands and no args") {
            @Parameters(commandNames = ["config"], commandDescription = "Config management")
            class Config

            @Parameters(commandNames = ["get"], commandDescription = "Get config")
            class Get

            @Parameters(commandNames = ["set"], commandDescription = "Set config")
            class Set

            val jc = JCommander()
            jc.addCommand("config", Config())
            val configJc = jc.commands["config"]!!
            configJc.addCommand("get", Get())
            configJc.addCommand("set", Set())

            val output = generate(jc)
            output shouldContain "subcommand_required=#true"
        }

        test("does not set subcommand_required when command has positional args") {
            @Parameters(commandNames = ["greet"], commandDescription = "Greet someone")
            class Greet {
                @Parameter(description = "Name to greet")
                var name: String? = null
            }

            @Parameters(commandNames = ["formally"], commandDescription = "Formal greet")
            class Formally

            val jc = JCommander()
            jc.addCommand("greet", Greet())
            val greetJc = jc.commands["greet"]!!
            greetJc.addCommand("formally", Formally())

            val output = generate(jc)
            val greetLine = output.split("\n").find { it.contains("cmd greet") }
            greetLine shouldNotBe null
            greetLine shouldNotContain "subcommand_required"
        }
    }

    context("aliases") {
        test("renders command aliases") {
            @Parameters(commandNames = ["install"], commandDescription = "Install packages")
            class Install

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("install", Install(), "i", "in")

            val output = generate(jc)
            output shouldContain "cmd install"
            output shouldContain "alias i in"
        }

        test("renders single alias") {
            @Parameters(commandNames = ["remove"], commandDescription = "Remove packages")
            class Remove

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("remove", Remove(), "rm")

            val output = generate(jc)
            output shouldContain "alias rm"
        }

        test("does not render alias when none defined") {
            @Parameters(commandNames = ["remove"], commandDescription = "Remove packages")
            class Remove

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("remove", Remove())

            val output = generate(jc)
            output shouldNotContain "alias"
        }
    }

    context("long help") {
        test("renders about for root command") {
            @Parameters(commandNames = ["app"], commandDescription = "An application")
            class App

            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain "name app"
            output shouldContain "bin app"
            output shouldContain """about "An application""""
        }

        test("renders help for subcommand") {
            @Parameters(commandNames = ["sub"], commandDescription = "A subcommand")
            class Sub

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("sub", Sub())

            val output = generate(jc)
            output shouldContain "cmd sub"
            output shouldContain """help="A subcommand""""
        }
    }

    context("special character escaping") {
        test("handles newlines in command help") {
            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            val output = generate(jc)
            val kdlContent = output.split("\n").drop(1).joinToString("\n")

            shouldNotThrowAny {
                validateKDL(kdlContent)
            }
        }

        test("handles special chars in flag help") {
            class App {
                @Parameter(names = ["--format"], description = "Output format")
                var format: String? = null
            }

            val jc = JCommander(App())
            val output = generate(jc)
            val kdlContent = output.split("\n").drop(1).joinToString("\n")

            shouldNotThrowAny {
                validateKDL(kdlContent)
            }
        }
    }

    context("KDL round-trip validation") {
        test("generates valid KDL for basic command") {
            class App {
                @Parameter(names = ["-v", "--verbose"], description = "Be verbose")
                var verbose = false

                @Parameter(names = ["-f", "--file"], description = "Input file")
                var file: String? = null
            }

            val jc = JCommander(App())
            jc.programName = "app"
            val output = generate(jc)
            val kdlContent = output.split("\n").drop(1).joinToString("\n")

            shouldNotThrowAny {
                validateKDL(kdlContent)
            }
        }

        test("generates valid KDL for nested commands") {
            @Parameters(commandNames = ["get"], commandDescription = "Get config")
            class Get

            @Parameters(commandNames = ["config"], commandDescription = "Config management")
            class Config

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("config", Config())
            val configJc = jc.commands["config"]!!
            configJc.addCommand("get", Get())

            val output = generate(jc)
            val kdlContent = output.split("\n").drop(1).joinToString("\n")

            shouldNotThrowAny {
                validateKDL(kdlContent)
            }
        }
    }

    context("generateKDL and JSON output") {
        test("generateKDL is an alias for generate") {
            class App
            val jc = JCommander(App())
            jc.programName = "app"
            generateKDL(jc) shouldBe generate(jc)
        }

        test("generates JSON output with correct structure") {
            @Parameters(commandNames = ["run"], commandDescription = "Run command")
            class Run

            @Parameters(commandNames = ["mycli"], commandDescription = "My CLI")
            class MyCli {
                @Parameter(names = ["--verbose"], description = "Be verbose")
                var verbose = false
            }

            val jc = JCommander(MyCli())
            jc.addCommand("run", Run())

            val json = generateJSON(jc)

            json shouldContain "mycli"
            json shouldContain "verbose"
            json shouldContain "run"
        }

        test("includes choices in JSON output") {
            class Deploy {
                @Parameter(names = ["--format"], description = "Output format")
                var format: TestFormat? = null
            }

            val json = generateJSON(JCommander(Deploy()))
            json shouldContain "JSON"
            json shouldContain "YAML"
        }

        test("includes flag details in JSON") {
            class App {
                @Parameter(names = ["--env"], description = "Target environment", required = true)
                var env: String? = null
            }

            val json = generateJSON(JCommander(App()))
            json shouldContain "required"
            json shouldContain "env"
        }

        test("handles custom bin name in JSON") {
            class App
            val jc = JCommander(App())
            val json = generateJSON(jc, "my-tool")
            json shouldContain "my-tool"
        }
    }

    context("convertRoot") {
        test("returns a spec with correct structure") {
            @Parameters(commandNames = ["mycli"], commandDescription = "My CLI")
            class MyCli {
                @Parameter(names = ["--verbose"], description = "Be verbose")
                var verbose = false
            }

            val spec = convertRoot(JCommander(MyCli()))

            spec.name shouldBe "mycli"
            spec.bin shouldBe "mycli"
            spec.version shouldBe ""
            spec.about shouldBe "My CLI"
            spec.flags.size shouldBe 1
            spec.flags[0].long shouldBe "verbose"
        }

        test("includes arguments in spec") {
            class Cmd {
                @Parameter(description = "Source path", required = true)
                var source: String? = null
            }

            val spec = convertRoot(JCommander(Cmd()))

            spec.args.size shouldBe 1
            spec.args[0].name shouldBe "SOURCE"
            spec.args[0].required.shouldBeTrue()
        }
    }

    context("edge cases") {
        test("handles empty command with no options or args") {
            @Parameters(commandNames = ["empty"], commandDescription = "Empty command")
            class Empty

            val jc = JCommander(Empty())
            val output = generate(jc)

            output shouldContain "name empty"
            output shouldContain "bin empty"
            output shouldNotContain "flag"
            output shouldNotContain "arg"
            output shouldNotContain "cmd"
        }

        test("handles command with only subcommands") {
            @Parameters(commandNames = ["start"], commandDescription = "Start")
            class Start

            @Parameters(commandNames = ["stop"], commandDescription = "Stop")
            class Stop

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("start", Start())
            jc.addCommand("stop", Stop())

            val output = generate(jc)

            output shouldContain "cmd start"
            output shouldContain "cmd stop"
        }

        test("handles option with required") {
            class App {
                @Parameter(names = ["--token"], description = "Auth token", required = true)
                var token: String? = null
            }

            val jc = JCommander(App())
            val output = generate(jc)

            output shouldContain """flag --token help="Auth token" required=#true"""
        }

        test("handles variadic option argument") {
            class App {
                @Parameter(names = ["--include"], description = "Include patterns", variableArity = true)
                var include: List<String> = mutableListOf()
            }

            val jc = JCommander(App())
            val output = generate(jc)

            output shouldContain """flag --include help="Include patterns""""
        }

        test("skips version field when not set") {
            class App
            val jc = JCommander(App())
            jc.programName = "app"
            val output = generate(jc)

            output shouldNotContain "version "
        }

        test("handles multiple flags on subcommand") {
            @Parameters(commandNames = ["build"], commandDescription = "Build")
            class Build {
                @Parameter(names = ["-o", "--output"], description = "Output directory")
                var output: String? = null

                @Parameter(names = ["--minify"], description = "Minify output")
                var minify = false

                @Parameter(names = ["--watch"], description = "Watch for changes")
                var watch = false
            }

            @Parameters(commandNames = ["app"], commandDescription = "An app")
            class App

            val jc = JCommander(App())
            jc.addCommand("build", Build())

            val output = generate(jc)

            output shouldContain """flag "-o --output" help="Output directory""""
            output shouldContain """flag --minify help="Minify output""""
            output shouldContain """flag --watch help="Watch for changes""""
        }

        test("converts optional main parameter") {
            class Cmd {
                @Parameter(description = "Config file", required = false)
                var config: String? = null
            }
            val jc = JCommander(Cmd())
            val output = generate(jc)
            output shouldContain """arg "[CONFIG]""""
        }

        test("renders flag with optional argument") {
            class App {
                @Parameter(names = ["-c", "--config"], description = "Config file", required = false)
                var config: String? = null
            }
            val jc = JCommander(App())
            val output = generate(jc)
            output shouldContain """flag "-c --config" help="Config file""""
        }

        test("includes arguments in JSON output") {
            class App {
                @Parameter(description = "Target environment", required = true)
                var env: String? = null
            }
            val jc = JCommander(App())
            val json = generateJSON(jc)

            json shouldContain "\"args\":"
            json shouldContain "\"name\": \"ENV\""
        }

        test("convertRoot returns correct spec structure") {
            class App {
                @Parameter(names = ["-v"], description = "Be verbose")
                var verbose = false
            }
            val jc = JCommander(App())
            jc.programName = "app"
            val spec = convertRoot(jc)

            spec.name shouldBe "app"
            spec.bin shouldBe "app"
            spec.flags.size shouldBe 1
            spec.flags.first().short shouldBe "v"
        }
    }
})
