import type { Command } from "commander";
import { convertRoot } from "./convert.js";
import { renderKDL, renderJSON, generate as coreGenerate } from "@usage-spec/core";
import type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices } from "@usage-spec/core";

export { convertRoot } from "./convert.js";
export { renderKDL } from "@usage-spec/core";
export type { Spec, SpecArg, SpecCommand, SpecFlag, SpecChoices };

/**
 * Generates a usage spec in KDL format from a Commander.js Command.
 */
export function generate(cmd: Command, binName?: string): string {
  const spec = convertRoot(cmd);
  if (binName) spec.bin = binName;
  return coreGenerate(spec, {
    format: "kdl",
    comment: "@generated by @usage-spec/commander from Commander.js metadata",
  });
}

/**
 * Generates a usage spec in KDL format from a Commander.js Command.
 */
export function generateKDL(cmd: Command, binName?: string): string {
  return generate(cmd, binName);
}

/**
 * Generates a usage spec in JSON format from a Commander.js Command.
 */
export function generateJSON(cmd: Command, binName?: string): string {
  const spec = convertRoot(cmd);
  if (binName) spec.bin = binName;
  return coreGenerate(spec, { format: "json" });
}

/**
 * Generates a usage spec and writes it to stdout.
 */
export function generateToStdout(cmd: Command, binName?: string): void {
  const output = generate(cmd, binName);
  process.stdout.write(output);
}
