import { describe, it, expect } from "vitest";
import yargs from "yargs";
import { generate, generateKDL, generateJSON, convertRoot } from "../src/index.js";
import { validateKDL } from "@usage-spec/core";

// Helper to create a yargs instance without calling .parse()
function createYargs(): ReturnType<typeof yargs> {
  return yargs([]).help(false).version(false);
}

describe("simple command", () => {
  it("generates spec for a basic CLI with version and options", () => {
    const y = createYargs()
      .scriptName("mycli")
      .version("1.0.0")
      .option("verbose", {
        alias: "v",
        type: "boolean",
        description: "Enable verbose output",
      })
      .option("config", {
        alias: "c",
        type: "string",
        description: "Config file path",
      });

    const output = generate(y, "mycli");

    expect(output).toContain("name mycli");
    expect(output).toContain("bin mycli");
    expect(output).toContain(`version "1.0.0"`);
    expect(output).toContain("verbose");
    expect(output).toContain("config");
  });

  it("includes generated comment header", () => {
    const y = createYargs().scriptName("app");
    const output = generate(y);
    expect(output).toContain("// @generated by @usage-spec/yargs from yargs metadata");
  });

  it("uses custom bin name when provided", () => {
    const y = createYargs().scriptName("app");
    const output = generate(y, "my-app");
    expect(output).toContain("bin my-app");
  });
});

describe("version", () => {
  it("extracts version string", () => {
    const y = createYargs().scriptName("app").version("2.0.0");
    const spec = convertRoot(y);
    expect(spec.version).toBe("2.0.0");
  });

  it("skips version field when not set", () => {
    const y = createYargs().scriptName("app");
    const output = generate(y);
    expect(output).not.toContain("version ");
  });
});

describe("about/description", () => {
  it("extracts usage description as about", () => {
    const y = createYargs().scriptName("app").usage("A simple CLI tool");
    const spec = convertRoot(y);
    expect(spec.about).toBe("A simple CLI tool");
  });
});

describe("nested subcommands", () => {
  it("renders subcommands recursively", () => {
    const y = createYargs()
      .scriptName("app")
      .usage("An app")
      .command("sub", "A subcommand", (yargs) => {
        return yargs.command("nested", "A nested command");
      });

    const output = generate(y);

    expect(output).toContain("cmd sub");
    expect(output).toContain("help=\"A subcommand\"");
    expect(output).toContain("cmd nested");
    expect(output).toContain("help=\"A nested command\"");
  });

  it("renders deeply nested command structure", () => {
    const y = createYargs()
      .scriptName("myapp")
      .version("1.0.0")
      .usage("My application")
      .command("db", "Database operations", (yargs) => {
        return yargs.command("migrate", "Run migrations", (yargs) => {
          return yargs
            .command("up", "Apply migrations")
            .command("down", "Rollback migrations");
        });
      });

    const output = generate(y);

    expect(output).toContain("cmd db");
    expect(output).toContain("help=\"Database operations\"");
    expect(output).toContain("cmd migrate");
    expect(output).toContain("help=\"Run migrations\"");
    expect(output).toContain("cmd up");
    expect(output).toContain("help=\"Apply migrations\"");
    expect(output).toContain("cmd down");
    expect(output).toContain("help=\"Rollback migrations\"");
  });
});

describe("options", () => {
  it("renders short and long flags", () => {
    const y = createYargs().option("verbose", {
      alias: "v",
      type: "boolean",
      description: "Be verbose",
    });

    const output = generate(y);

    expect(output).toContain("flag");
    expect(output).toContain("verbose");
  });

  it("marks required options", () => {
    const y = createYargs().option("env", {
      type: "string",
      description: "Target environment",
      demandOption: true,
    });

    const output = generate(y);

    expect(output).toContain("required=#true");
  });

  it("renders default values for string options", () => {
    const y = createYargs()
      .option("format", {
        type: "string",
        description: "Output format",
        default: "json",
      })
      .option("retries", {
        type: "number",
        description: "Number of retries",
        default: 3,
      });

    const spec = convertRoot(y);
    const formatFlag = spec.flags.find((f) => f.long === "format");
    expect(formatFlag).toBeDefined();
    expect(formatFlag!.default).toEqual(["json"]);

    const retriesFlag = spec.flags.find((f) => f.long === "retries");
    expect(retriesFlag).toBeDefined();
    expect(retriesFlag!.default).toEqual(["3"]);
  });

  it("renders boolean default true", () => {
    const y = createYargs().option("color", {
      type: "boolean",
      description: "Enable color",
      default: true,
    });

    const spec = convertRoot(y);
    const colorFlag = spec.flags.find((f) => f.long === "color");
    expect(colorFlag).toBeDefined();
    expect(colorFlag!.defaultBool).toBe(true);
  });

  it("skips false default for boolean flags", () => {
    const y = createYargs().option("force", {
      type: "boolean",
      description: "Force the operation",
      default: false,
    });

    const spec = convertRoot(y);
    const forceFlag = spec.flags.find((f) => f.long === "force");
    expect(forceFlag).toBeDefined();
    expect(forceFlag!.default).toEqual([]);
    expect(forceFlag!.defaultBool).toBeNull();
  });

  it("preserves string zero as default", () => {
    const y = createYargs().option("port", {
      type: "string",
      description: "Port number",
      default: "0",
    });

    const output = generate(y);
    expect(output).toContain(`default="0"`);
  });

  it("renders choices", () => {
    const y = createYargs().option("format", {
      type: "string",
      description: "Output format",
      choices: ["json", "yaml", "toml"],
    });

    const spec = convertRoot(y);
    const formatFlag = spec.flags.find((f) => f.long === "format");
    expect(formatFlag).toBeDefined();
    expect(formatFlag!.arg?.choices?.values).toEqual(["json", "yaml", "toml"]);
  });

  it("hides hidden options", () => {
    const y = createYargs().option("secret", {
      type: "string",
      description: "Secret option",
      hidden: true,
    });

    const spec = convertRoot(y);
    const secretFlag = spec.flags.find((f) => f.long === "secret");
    expect(secretFlag).toBeDefined();
    expect(secretFlag!.hide).toBe(true);
  });

  it("handles count options", () => {
    const y = createYargs().option("verbose", {
      alias: "v",
      count: true,
      description: "Verbosity level",
    });

    const spec = convertRoot(y);
    const verboseFlag = spec.flags.find((f) => f.long === "verbose");
    expect(verboseFlag).toBeDefined();
    expect(verboseFlag!.count).toBe(true);
  });

  it("handles array/multiple options", () => {
    const y = createYargs().option("include", {
      type: "string",
      array: true,
      description: "Include patterns",
    });

    const spec = convertRoot(y);
    const includeFlag = spec.flags.find((f) => f.long === "include");
    expect(includeFlag).toBeDefined();
    expect(includeFlag!.var).toBe(true);
    expect(includeFlag!.arg?.var).toBe(true);
  });
});

describe("boolean flags", () => {
  it("does not render arg for boolean flags", () => {
    const y = createYargs().option("force", {
      type: "boolean",
      description: "Force the operation",
    });

    const spec = convertRoot(y);
    const forceFlag = spec.flags.find((f) => f.long === "force");
    expect(forceFlag).toBeDefined();
    expect(forceFlag!.arg).toBeNull();
  });
});

describe("negated options", () => {
  it("does not render negate for yargs (no native --no- support)", () => {
    // yargs doesn't have a native negated option concept like Commander's --no-
    // The negate field is always empty for yargs
    const y = createYargs().option("color", {
      type: "boolean",
      description: "Enable color",
    });

    const spec = convertRoot(y);
    const colorFlag = spec.flags.find((f) => f.long === "color");
    expect(colorFlag).toBeDefined();
    expect(colorFlag!.negate).toBe("");
  });
});

describe("environment variables", () => {
  it("renders env prefix for options with envPrefix", () => {
    const y = createYargs()
      .env("MYCLI")
      .option("color", {
        type: "string",
        description: "Color output",
      });

    const spec = convertRoot(y);
    const colorFlag = spec.flags.find((f) => f.long === "color");
    expect(colorFlag).toBeDefined();
    expect(colorFlag!.env).toBe("MYCLI_COLOR");
  });

  it("has no env when envPrefix is not set", () => {
    const y = createYargs().option("color", {
      type: "string",
      description: "Color output",
    });

    const spec = convertRoot(y);
    const colorFlag = spec.flags.find((f) => f.long === "color");
    expect(colorFlag).toBeDefined();
    expect(colorFlag!.env).toBe("");
  });
});

describe("deprecated options", () => {
  it("marks deprecated options", () => {
    const y = createYargs().option("old-flag", {
      type: "string",
      description: "Old flag",
      deprecated: "Use --new-flag instead",
    });

    const spec = convertRoot(y);
    const oldFlag = spec.flags.find((f) => f.long === "old-flag");
    expect(oldFlag).toBeDefined();
    expect(oldFlag!.deprecated).toBe("Use --new-flag instead");
  });

  it("handles boolean deprecated", () => {
    const y = createYargs().option("old-flag", {
      type: "string",
      description: "Old flag",
      deprecated: true,
    });

    const spec = convertRoot(y);
    const oldFlag = spec.flags.find((f) => f.long === "old-flag");
    expect(oldFlag).toBeDefined();
    expect(oldFlag!.deprecated).toBe("");
  });
});

describe("skips builtin flags", () => {
  it("does not render --help and --version flags when enabled", () => {
    // Create yargs with help and version enabled (default)
    const y = yargs([])
      .scriptName("app")
      .version("1.0.0")
      .option("custom", {
        type: "string",
        description: "A custom flag",
      });

    const spec = convertRoot(y);
    const flagNames = spec.flags.map((f) => f.long);
    expect(flagNames).not.toContain("help");
    expect(flagNames).not.toContain("version");
    expect(flagNames).toContain("custom");
  });
});

describe("commands", () => {
  it("renders subcommands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("add <file>", "Add a file", () => {})
      .command("remove", "Remove files", () => {});

    const output = generate(y);

    expect(output).toContain("cmd add");
    expect(output).toContain("cmd remove");
  });

  it("renders command aliases", () => {
    const y = createYargs()
      .scriptName("app")
      .command(["install", "i", "add"], "Install packages", () => {});

    const spec = convertRoot(y);
    const installCmd = spec.cmds.find((c) => c.name === "install");
    expect(installCmd).toBeDefined();
    expect(installCmd!.aliases).toContain("i");
    expect(installCmd!.aliases).toContain("add");
  });

  it("renders single command alias", () => {
    const y = createYargs()
      .scriptName("app")
      .command(["remove", "rm"], "Remove packages", () => {});

    const spec = convertRoot(y);
    const removeCmd = spec.cmds.find((c) => c.name === "remove");
    expect(removeCmd).toBeDefined();
    expect(removeCmd!.aliases).toContain("rm");
  });

  it("handles hidden commands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("secret", false, () => {});

    const spec = convertRoot(y);
    const secretCmd = spec.cmds.find((c) => c.name === "secret");
    expect(secretCmd).toBeDefined();
    expect(secretCmd!.hide).toBe(true);
  });

  it("renders nested subcommands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("db", "Database ops", (yargs) => {
        return yargs.command("migrate", "Run migrations");
      });

    const output = generate(y);

    expect(output).toContain("cmd db");
    expect(output).toContain("cmd migrate");
  });

  it("handles command with multiple flags", () => {
    const y = createYargs()
      .scriptName("app")
      .command("build", "Build the project", (yargs) => {
        return yargs
          .option("output", {
            alias: "o",
            type: "string",
            description: "Output directory",
          })
          .option("minify", {
            type: "boolean",
            description: "Minify output",
          })
          .option("watch", {
            type: "boolean",
            description: "Watch for changes",
          });
      });

    const spec = convertRoot(y);
    const buildCmd = spec.cmds.find((c) => c.name === "build");
    expect(buildCmd).toBeDefined();
    expect(buildCmd!.flags).toHaveLength(3);
    expect(buildCmd!.flags.map((f) => f.long)).toContain("output");
    expect(buildCmd!.flags.map((f) => f.long)).toContain("minify");
    expect(buildCmd!.flags.map((f) => f.long)).toContain("watch");
  });
});

describe("positional arguments", () => {
  it("converts required positional args", () => {
    const y = createYargs()
      .scriptName("cmd")
      .command("add <file>", "Add a file", () => {});

    const spec = convertRoot(y);
    const addCmd = spec.cmds.find((c) => c.name === "add");
    expect(addCmd).toBeDefined();
    expect(addCmd!.args).toHaveLength(1);
    expect(addCmd!.args[0].name).toBe("file");
    expect(addCmd!.args[0].required).toBe(true);
  });

  it("converts optional positional args", () => {
    const y = createYargs()
      .scriptName("cmd")
      .command("list [filter]", "List items", () => {});

    const spec = convertRoot(y);
    const listCmd = spec.cmds.find((c) => c.name === "list");
    expect(listCmd).toBeDefined();
    expect(listCmd!.args).toHaveLength(1);
    expect(listCmd!.args[0].name).toBe("filter");
    expect(listCmd!.args[0].required).toBe(false);
  });

  it("converts variadic positional args", () => {
    const y = createYargs()
      .scriptName("cmd")
      .command("add <files..>", "Add files", () => {});

    const spec = convertRoot(y);
    const addCmd = spec.cmds.find((c) => c.name === "add");
    expect(addCmd).toBeDefined();
    expect(addCmd!.args).toHaveLength(1);
    expect(addCmd!.args[0].name).toBe("files");
    expect(addCmd!.args[0].var).toBe(true);
  });

  it("converts mixed required and optional args", () => {
    const y = createYargs()
      .scriptName("cmd")
      .command("copy <source> [dest]", "Copy files", () => {});

    const spec = convertRoot(y);
    const copyCmd = spec.cmds.find((c) => c.name === "copy");
    expect(copyCmd).toBeDefined();
    expect(copyCmd!.args).toHaveLength(2);
    expect(copyCmd!.args[0].name).toBe("source");
    expect(copyCmd!.args[0].required).toBe(true);
    expect(copyCmd!.args[1].name).toBe("dest");
    expect(copyCmd!.args[1].required).toBe(false);
  });
});

describe("option with only short flag", () => {
  it("renders short-only flags", () => {
    const y = createYargs().option("v", {
      type: "boolean",
      description: "Be verbose",
    });

    const spec = convertRoot(y);
    // When a single-char name is used, it's treated as a short flag
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].short).toBe("v");
  });
});

describe("option with only long flag", () => {
  it("renders long-only flags", () => {
    const y = createYargs().option("verbose", {
      type: "boolean",
      description: "Be verbose",
    });

    const spec = convertRoot(y);
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
    expect(spec.flags[0].short).toBe("");
  });
});

describe("special character escaping", () => {
  it("handles special chars in flag help", () => {
    const y = createYargs().option("format", {
      type: "string",
      description: "Output format:\n  json\n  yaml",
    });

    const output = generate(y);
    expect(output).toContain("help=");
    // Verify the output is valid KDL
    expect(() => validateKDL(output.split("\n").slice(1).join("\n"))).not.toThrow();
  });
});

describe("KDL round-trip validation", () => {
  it("generates valid KDL for basic CLI", () => {
    const y = createYargs()
      .scriptName("app")
      .version("1.0.0")
      .option("verbose", {
        alias: "v",
        type: "boolean",
        description: "Be verbose",
      })
      .option("file", {
        alias: "f",
        type: "string",
        description: "Input file",
      });

    const output = generate(y);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });

  it("generates valid KDL for CLI with commands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("add <file>", "Add a file", () => {})
      .command("remove", "Remove files", () => {});

    const output = generate(y);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });

  it("generates valid KDL for nested commands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("config", "Config", (yargs) => {
        return yargs.command("get", "Get value");
      });

    const output = generate(y);
    const kdlContent = output.split("\n").slice(1).join("\n");
    expect(() => validateKDL(kdlContent)).not.toThrow();
  });
});

describe("generateKDL", () => {
  it("is an alias for generate", () => {
    const y = createYargs().scriptName("app").usage("A CLI");
    expect(generateKDL(y)).toBe(generate(y));
  });
});

describe("JSON output", () => {
  it("generates JSON output with correct structure", () => {
    const y = createYargs()
      .scriptName("mycli")
      .version("2.0.0")
      .usage("A CLI tool")
      .option("verbose", {
        alias: "v",
        type: "boolean",
        description: "Be verbose",
      })
      .command("run", "Run something", () => {});

    const json = generateJSON(y);
    const parsed = JSON.parse(json);

    expect(parsed.name).toBe("mycli");
    expect(parsed.bin).toBe("mycli");
    expect(parsed.version).toBe("2.0.0");
    expect(parsed.about).toBe("A CLI tool");
    expect(parsed.flags).toHaveLength(1);
    expect(parsed.cmds).toHaveLength(1);
    expect(parsed.cmds[0].name).toBe("run");
  });

  it("includes choices in JSON output", () => {
    const y = createYargs()
      .scriptName("deploy")
      .option("env", {
        type: "string",
        description: "Environment",
        choices: ["dev", "prod"],
      });

    const json = generateJSON(y);
    const parsed = JSON.parse(json);

    expect(parsed.flags[0].arg.choices).toEqual(["dev", "prod"]);
  });

  it("includes flag details in JSON", () => {
    const y = createYargs()
      .scriptName("app")
      .option("env", {
        type: "string",
        description: "Target environment",
        demandOption: true,
      });

    const json = generateJSON(y);
    const parsed = JSON.parse(json);

    expect(parsed.flags).toHaveLength(1);
    expect(parsed.flags[0].required).toBe(true);
    expect(parsed.flags[0].arg.name).toBe("ENV");
  });

  it("handles custom bin name in JSON", () => {
    const y = createYargs().scriptName("app").usage("A tool");
    const json = generateJSON(y, "my-tool");
    const parsed = JSON.parse(json);

    expect(parsed.bin).toBe("my-tool");
  });
});

describe("convertRoot", () => {
  it("returns a spec with correct structure", () => {
    const y = createYargs()
      .scriptName("mycli")
      .version("2.0.0")
      .usage("A CLI tool")
      .option("verbose", {
        alias: "v",
        type: "boolean",
        description: "Be verbose",
      });

    const spec = convertRoot(y);

    expect(spec.name).toBe("mycli");
    expect(spec.bin).toBe("mycli");
    expect(spec.version).toBe("2.0.0");
    expect(spec.about).toBe("A CLI tool");
    expect(spec.flags).toHaveLength(1);
    expect(spec.flags[0].long).toBe("verbose");
    expect(spec.flags[0].short).toBe("v");
  });

  it("includes arguments from commands in spec", () => {
    const y = createYargs()
      .scriptName("cmd")
      .command("add <file>", "Add a file", () => {});

    const spec = convertRoot(y);
    const addCmd = spec.cmds.find((c) => c.name === "add");

    expect(addCmd!.args).toHaveLength(1);
    expect(addCmd!.args[0].name).toBe("file");
    expect(addCmd!.args[0].required).toBe(true);
  });
});

describe("edge cases", () => {
  it("handles empty CLI with no options or args", () => {
    const y = createYargs().scriptName("empty");
    const output = generate(y);

    expect(output).toContain("name empty");
    expect(output).toContain("bin empty");
    expect(output).not.toMatch(/\bflag\b/);
    expect(output).not.toMatch(/^(\s*)arg /m);
    expect(output).not.toMatch(/\bcmd\b/);
  });

  it("handles CLI with only subcommands", () => {
    const y = createYargs()
      .scriptName("app")
      .command("start", "Start", () => {})
      .command("stop", "Stop", () => {});

    const output = generate(y);

    expect(output).toContain("cmd start");
    expect(output).toContain("cmd stop");
  });

  it("handles command with object builder", () => {
    const y = createYargs()
      .scriptName("app")
      .command("build", "Build the project", {
        output: {
          type: "string",
          alias: "o",
          description: "Output directory",
        },
      });

    const spec = convertRoot(y);
    const buildCmd = spec.cmds.find((c) => c.name === "build");
    expect(buildCmd).toBeDefined();
    expect(buildCmd!.flags).toHaveLength(1);
    expect(buildCmd!.flags[0].long).toBe("output");
  });
});

describe("full output format", () => {
  it("matches expected KDL output for a complete example", () => {
    const y = createYargs()
      .scriptName("example")
      .version("1.0.0")
      .usage("An example CLI")
      .option("file", {
        alias: "f",
        type: "string",
        description: "Some input file",
      })
      .option("verbose", {
        type: "boolean",
        description: "Enable verbose output",
      });

    const output = generate(y, "example");

    expect(output).toContain("name example");
    expect(output).toContain("bin example");
    expect(output).toContain(`version "1.0.0"`);
    expect(output).toContain(`about "An example CLI"`);
    expect(output).toContain("file");
    expect(output).toContain("verbose");
  });
});
